!        generated by tapenade     (inria, ecuador team)
!  tapenade 3.16 (develop) - 22 aug 2023 15:51
!
module sst_fast_b
! this module contains the source code related to the sst turbulence
! model. it is slightly more modularized than the original which makes
! performing reverse mode ad simplier.
  use constants
  implicit none
  real(kind=realtype), dimension(:, :, :, :, :), allocatable :: qq
  real(kind=realtype), dimension(:, :, :), pointer :: ddw, ww, ddvt
  real(kind=realtype), dimension(:, :), pointer :: rrlv
  real(kind=realtype), dimension(:, :), pointer :: dd2wall

contains
!  differentiation of sstsource in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *rev *w *scratch
!   with respect to varying inputs: *rev *w *scratch
!   rw status of diff variables: *rev:incr *w:incr *scratch:in-out
!   plus diff mem management of: rev:in w:in scratch:in
  subroutine sstsource_fast_b()
!
!       sstsolve solves the turbulent transport equations for
!       menter's sst variant of the k-omega model in a decoupled
!       manner using a diagonal dominant adi-scheme.
!
    use blockpointers
    use constants
    use variableconstants
    use inputphysics
    use inputdiscretization, only : approxturb
    use paramturb
    use utils_fast_b, only : smoothmin, smoothmax
    use inputiteration, only : smoothsstphi
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k
    real(kind=realtype) :: rsstgam1, rsstgam2, t1, t2
    real(kind=realtype) :: t1d, t2d
    real(kind=realtype) :: rsstgam, rsstbeta
    real(kind=realtype) :: rsstgamd, rsstbetad
    real(kind=realtype) :: rhoi, ss, spk, sdk
    real(kind=realtype) :: rhoid, ssd, spkd, sdkd
    real(kind=realtype) :: xm, ym, zm, xp, yp, zp, xa, ya, za
    real(kind=realtype) :: re_w, u, f_wake, delta, r_t, re_s, f_theta_t
    real(kind=realtype) :: re_wd, ud, f_waked, deltad, r_td, re_sd, &
&   f_theta_td
    real(kind=realtype) :: re_theta_c, f_reattach, gamma_sep, gamma_eff
    real(kind=realtype) :: re_theta_cd, f_reattachd, gamma_sepd, &
&   gamma_effd
    real(kind=realtype) :: vort
    real(kind=realtype) :: vortd
    intrinsic sqrt
    intrinsic mod
    intrinsic min
    intrinsic exp
    intrinsic max
    real(kind=realtype) :: x1
    real(kind=realtype) :: x1d
    real(kind=realtype) :: x2
    real(kind=realtype) :: x2d
    real(kind=realtype) :: x3
    real(kind=realtype) :: x3d
    real(kind=realtype) :: x4
    real(kind=realtype) :: x4d
    real(kind=realtype) :: min1
    real(kind=realtype) :: min1d
    real(kind=realtype) :: min2
    real(kind=realtype) :: min2d
    real(kind=realtype) :: max1
    real(kind=realtype) :: max1d
    real(kind=realtype) :: temp
    real(kind=realtype) :: tempd
    real(kind=realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: temp2
    real(kind=realtype) :: tempd0
    real(kind=realtype) :: tempd1
    real(kind=realtype) :: tempd2
    real(kind=realtype) :: tmp
    real(kind=realtype) :: tmpd
    real(kind=realtype) :: tmp0
    real(kind=realtype) :: tmpd0
    integer :: branch
    integer :: ii
! set model constants
    if (use2003sst) then
      rsstgam1 = 5.0_realtype/9.0_realtype
      rsstgam2 = 0.44_realtype
      pklim = 10.0
    else
      rsstgam1 = rsstbeta1/rsstbetas - rsstsigw1*rsstk*rsstk/sqrt(&
&       rsstbetas)
      rsstgam2 = rsstbeta2/rsstbetas - rsstsigw2*rsstk*rsstk/sqrt(&
&       rsstbetas)
      pklim = 20.0
    end if
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the blended value of rsstgam and rsstbeta,
! which occur in the production terms of k and omega.
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstgam = t1*rsstgam1 + t2*rsstgam2
      rsstbeta = t1*rsstbeta1 + t2*rsstbeta2
! compute the source terms for both the k and the omega
! equation. note that dw(i,j,k,iprod) currently contains the
! unscaled source term. furthermore the production term of
! k is limited to a certain times the destruction term.
! these are the same equations as in https://turbmodels.larc.nasa.gov/sst.html
! except that everything is divided by rho here
      rhoi = one/w(i, j, k, irho)
      ss = scratch(i, j, k, iprod)
      if (approxturb) then
        spk = zero
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      else
        spk = rev(i, j, k)*ss*rhoi
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      end if
      sdk = rsstbetas*w(i, j, k, itu1)*w(i, j, k, itu2)
      if (spk .gt. pklim*sdk) then
        spk = pklim*sdk
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        spk = spk
      end if
      if (transitionmodel .eq. gammaretheta) then
        vort = sqrt(scratch(i, j, k, ivorticity))
        re_w = w(i, j, k, irho)*w(i, j, k, itu2)*d2wall(i, j, k)**2/rlv(&
&         i, j, k)
        u = sqrt(w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 + w(i, j, k, &
&         ivz)**2)
        f_wake = exp(-((re_w/100000.0)**2))
! todo: pull out of scratch
        r_t = w(i, j, k, irho)*w(i, j, k, itu1)/(rlv(i, j, k)*w(i, j, k&
&         , itu2))
! todo: pull out of scratch
        re_s = w(i, j, k, irho)*sqrt(scratch(i, j, k, istrain))*d2wall(i&
&         , j, k)**2/rlv(i, j, k)
        delta = 375.0*vort*rlv(i, j, k)*w(i, j, k, itransition2)*d2wall(&
&         i, j, k)/(w(i, j, k, irho)*u**2)
        x4 = f_wake*exp(-((d2wall(i, j, k)/delta)**4))
        if (x4 .lt. 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2&
&           -1))**2) then
          x1 = 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2-1))&
&           **2
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          x1 = x4
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        if (x1 .gt. 1.0) then
          f_theta_t = 1.0
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          f_theta_t = x1
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        if (w(i, j, k, itransition2) .le. 1870.0) then
          re_theta_c = -3.96035 + 1.0120656*w(i, j, k, itransition2) + (&
&           -0.868230e-3)*w(i, j, k, itransition2)**2 + 0.696506e-6*w(i&
&           , j, k, itransition2)**3 + (-0.174105e-9)*w(i, j, k, &
&           itransition2)**4
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        else
          re_theta_c = w(i, j, k, itransition2) - (593.11+0.482*(w(i, j&
&           , k, itransition2)-1870.0))
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        end if
        f_reattach = exp(-((r_t/20.0)**4))
        if (0.0 .lt. re_s/(3.235*re_theta_c) - 1.0) then
          max1 = re_s/(3.235*re_theta_c) - 1.0
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          max1 = 0.0
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        x2 = rlms1*max1*f_reattach
        if (x2 .gt. 2.0) then
          min1 = 2.0
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          min1 = x2
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        gamma_sep = min1*f_theta_t
        if (w(i, j, k, itransition1) .lt. gamma_sep) then
          gamma_eff = gamma_sep
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          gamma_eff = w(i, j, k, itransition1)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
! if gamma_eff = 1, the original sst should come out
        call pushreal8(spk)
        spk = gamma_eff*spk
        if (gamma_eff .lt. 0.1) then
          x3 = 0.1
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          x3 = gamma_eff
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        if (x3 .gt. 1.0) then
          min2 = 1.0
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          min2 = x3
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        call pushreal8(sdk)
        sdk = min2*sdk
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
      call pushreal8(scratch(i, j, k, idvt))
      scratch(i, j, k, idvt) = spk - sdk
      if (use2003sst) then
        tmpd = scratchd(i, j, k, idvt+1)
        scratchd(i, j, k, idvt+1) = 0.0_8
        temp0 = w(i, j, k, itu2)
        tempd0 = tmpd/rev(i, j, k)
        tempd1 = two*rsstsigw2*tmpd
        rsstbetad = -(temp0**2*tmpd)
        wd(i, j, k, itu2) = wd(i, j, k, itu2) - 2*temp0*rsstbeta*tmpd
        t2d = scratch(i, j, k, icd)*tempd1
        scratchd(i, j, k, icd) = scratchd(i, j, k, icd) + t2*tempd1
        rsstgamd = spk*tempd0
        spkd = rsstgam*tempd0
        revd(i, j, k) = revd(i, j, k) - rsstgam*spk*tempd0/rev(i, j, k)
        ssd = 0.0_8
      else
        tmpd0 = scratchd(i, j, k, idvt+1)
        scratchd(i, j, k, idvt+1) = 0.0_8
        temp1 = w(i, j, k, itu2)
        rsstgamd = ss*tmpd0
        ssd = rsstgam*tmpd0
        tempd0 = two*rsstsigw2*tmpd0
        rsstbetad = -(temp1**2*tmpd0)
        wd(i, j, k, itu2) = wd(i, j, k, itu2) - 2*temp1*rsstbeta*tmpd0
        t2d = scratch(i, j, k, icd)*tempd0
        scratchd(i, j, k, icd) = scratchd(i, j, k, icd) + t2*tempd0
        spkd = 0.0_8
      end if
      call popreal8(scratch(i, j, k, idvt))
      spkd = spkd + scratchd(i, j, k, idvt)
      sdkd = -scratchd(i, j, k, idvt)
      scratchd(i, j, k, idvt) = 0.0_8
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        call popreal8(sdk)
        min2d = sdk*sdkd
        sdkd = min2*sdkd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          x3d = 0.0_8
        else
          x3d = min2d
        end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          gamma_effd = 0.0_8
        else
          gamma_effd = x3d
        end if
        call popreal8(spk)
        gamma_effd = gamma_effd + spk*spkd
        spkd = gamma_eff*spkd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          gamma_sepd = gamma_effd
        else
          wd(i, j, k, itransition1) = wd(i, j, k, itransition1) + &
&           gamma_effd
          gamma_sepd = 0.0_8
        end if
        min1d = f_theta_t*gamma_sepd
        f_theta_td = min1*gamma_sepd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          x2d = 0.0_8
        else
          x2d = min1d
        end if
        max1d = f_reattach*rlms1*x2d
        f_reattachd = max1*rlms1*x2d
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          tempd0 = max1d/(3.235*re_theta_c)
          re_sd = tempd0
          re_theta_cd = -(re_s*tempd0/re_theta_c)
        else
          re_theta_cd = 0.0_8
          re_sd = 0.0_8
        end if
        r_td = -(4*r_t**3*exp(-((r_t/20.0)**4))*f_reattachd/20.0**4)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + 0.518*&
&           re_theta_cd
        else
          wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + (3*w(i&
&           , j, k, itransition2)**2*0.696506e-6-4*w(i, j, k, &
&           itransition2)**3*0.174105e-9-2*w(i, j, k, itransition2)*&
&           0.868230e-3+1.0120656)*re_theta_cd
        end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          x1d = 0.0_8
        else
          x1d = f_theta_td
        end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          wd(i, j, k, itransition1) = wd(i, j, k, itransition1) - rlmce2&
&           *2*(rlmce2*w(i, j, k, itransition1)-1.0)*x1d/(rlmce2-1)**2
          x4d = 0.0_8
        else
          x4d = x1d
        end if
        tempd0 = d2wall(i, j, k)**2*re_sd
        temp2 = d2wall(i, j, k)/delta
        temp1 = -(temp2**4)
        f_waked = exp(temp1)*x4d
        deltad = temp2**4*4*exp(temp1)*f_wake*x4d/delta
        temp2 = w(i, j, k, irho)
        temp1 = temp2*(u*u)
        temp = w(i, j, k, itransition2)
        tempd2 = rlv(i, j, k)*375.0*d2wall(i, j, k)*deltad/temp1
        vortd = temp*tempd2
        wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + vort*&
&         tempd2
        tempd1 = -(vort*temp*tempd2/temp1)
        ud = 2*u*temp2*tempd1
        temp1 = scratch(i, j, k, istrain)
        temp0 = sqrt(temp1)
        wd(i, j, k, irho) = wd(i, j, k, irho) + u**2*tempd1 + temp0*&
&         tempd0/rlv(i, j, k)
        if (.not.temp1 .eq. 0.0_8) scratchd(i, j, k, istrain) = scratchd&
&           (i, j, k, istrain) + w(i, j, k, irho)*tempd0/(2.0*temp0*rlv(&
&           i, j, k))
        temp2 = rlv(i, j, k)*w(i, j, k, itu2)
        temp0 = w(i, j, k, itu1)
        temp = w(i, j, k, irho)
        tempd1 = r_td/temp2
        wd(i, j, k, irho) = wd(i, j, k, irho) + temp0*tempd1
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + temp*tempd1
        wd(i, j, k, itu2) = wd(i, j, k, itu2) - rlv(i, j, k)*temp*temp0*&
&         tempd1/temp2
        re_wd = -(2*re_w*exp(-((re_w/100000.0)**2))*f_waked/100000.0**2)
        temp = w(i, j, k, ivz)
        temp0 = w(i, j, k, ivy)
        temp1 = w(i, j, k, ivx)
        if (temp1**2 + temp0**2 + temp**2 .eq. 0.0_8) then
          tempd0 = 0.0_8
        else
          tempd0 = ud/(2.0*sqrt(temp1**2+temp0**2+temp**2))
        end if
        wd(i, j, k, ivx) = wd(i, j, k, ivx) + 2*temp1*tempd0
        wd(i, j, k, ivy) = wd(i, j, k, ivy) + 2*temp0*tempd0
        wd(i, j, k, ivz) = wd(i, j, k, ivz) + 2*temp*tempd0
        tempd = d2wall(i, j, k)**2*re_wd
        wd(i, j, k, irho) = wd(i, j, k, irho) + w(i, j, k, itu2)*tempd/&
&         rlv(i, j, k)
        wd(i, j, k, itu2) = wd(i, j, k, itu2) + w(i, j, k, irho)*tempd/&
&         rlv(i, j, k)
        if (.not.scratch(i, j, k, ivorticity) .eq. 0.0_8) scratchd(i, j&
&         , k, ivorticity) = scratchd(i, j, k, ivorticity) + vortd/(2.0*&
&           sqrt(scratch(i, j, k, ivorticity)))
      end if
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        sdkd = sdkd + pklim*spkd
        spkd = 0.0_8
      end if
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + w(i, j, k, itu2)*rsstbetas&
&       *sdkd
      wd(i, j, k, itu2) = wd(i, j, k, itu2) + w(i, j, k, itu1)*rsstbetas&
&       *sdkd
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        revd(i, j, k) = revd(i, j, k) + ss*rhoi*spkd
        tempd = rev(i, j, k)*spkd
        ssd = ssd + rhoi*tempd
        rhoid = ss*tempd
      else
        rhoid = 0.0_8
      end if
      t2d = t2d + rsstbeta2*rsstbetad + rsstgam2*rsstgamd
      scratchd(i, j, k, iprod) = scratchd(i, j, k, iprod) + ssd
      temp = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp**2
      t1d = rsstbeta1*rsstbetad + rsstgam1*rsstgamd - t2d
      scratchd(i, j, k, if1sst) = scratchd(i, j, k, if1sst) + t1d
    end do
  end subroutine sstsource_fast_b

  subroutine sstsource()
!
!       sstsolve solves the turbulent transport equations for
!       menter's sst variant of the k-omega model in a decoupled
!       manner using a diagonal dominant adi-scheme.
!
    use blockpointers
    use constants
    use variableconstants
    use inputphysics
    use inputdiscretization, only : approxturb
    use paramturb
    use utils_fast_b, only : smoothmin, smoothmax
    use inputiteration, only : smoothsstphi
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k
    real(kind=realtype) :: rsstgam1, rsstgam2, t1, t2
    real(kind=realtype) :: rsstgam, rsstbeta
    real(kind=realtype) :: rhoi, ss, spk, sdk
    real(kind=realtype) :: xm, ym, zm, xp, yp, zp, xa, ya, za
    real(kind=realtype) :: re_w, u, f_wake, delta, r_t, re_s, f_theta_t
    real(kind=realtype) :: re_theta_c, f_reattach, gamma_sep, gamma_eff
    real(kind=realtype) :: vort
    intrinsic sqrt
    intrinsic mod
    intrinsic min
    intrinsic exp
    intrinsic max
    real(kind=realtype) :: x1
    real(kind=realtype) :: x2
    real(kind=realtype) :: x3
    real(kind=realtype) :: x4
    real(kind=realtype) :: min1
    real(kind=realtype) :: min2
    real(kind=realtype) :: max1
    integer :: ii
! set model constants
    if (use2003sst) then
      rsstgam1 = 5.0_realtype/9.0_realtype
      rsstgam2 = 0.44_realtype
      pklim = 10.0
    else
      rsstgam1 = rsstbeta1/rsstbetas - rsstsigw1*rsstk*rsstk/sqrt(&
&       rsstbetas)
      rsstgam2 = rsstbeta2/rsstbetas - rsstsigw2*rsstk*rsstk/sqrt(&
&       rsstbetas)
      pklim = 20.0
    end if
!$ad ii-loop
!       source terms.
!       determine the source term and its derivative w.r.t. k and
!       omega for all internal cells of the block.
!       note that the blending function f1 and the cross diffusion
!       were computed earlier in f1sst.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the blended value of rsstgam and rsstbeta,
! which occur in the production terms of k and omega.
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstgam = t1*rsstgam1 + t2*rsstgam2
      rsstbeta = t1*rsstbeta1 + t2*rsstbeta2
! compute the source terms for both the k and the omega
! equation. note that dw(i,j,k,iprod) currently contains the
! unscaled source term. furthermore the production term of
! k is limited to a certain times the destruction term.
! these are the same equations as in https://turbmodels.larc.nasa.gov/sst.html
! except that everything is divided by rho here
      rhoi = one/w(i, j, k, irho)
      ss = scratch(i, j, k, iprod)
      if (approxturb) then
        spk = zero
      else
        spk = rev(i, j, k)*ss*rhoi
      end if
      sdk = rsstbetas*w(i, j, k, itu1)*w(i, j, k, itu2)
      if (spk .gt. pklim*sdk) then
        spk = pklim*sdk
      else
        spk = spk
      end if
      if (transitionmodel .eq. gammaretheta) then
        vort = sqrt(scratch(i, j, k, ivorticity))
        re_w = w(i, j, k, irho)*w(i, j, k, itu2)*d2wall(i, j, k)**2/rlv(&
&         i, j, k)
        u = sqrt(w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 + w(i, j, k, &
&         ivz)**2)
        f_wake = exp(-((re_w/100000.0)**2))
! todo: pull out of scratch
        r_t = w(i, j, k, irho)*w(i, j, k, itu1)/(rlv(i, j, k)*w(i, j, k&
&         , itu2))
! todo: pull out of scratch
        re_s = w(i, j, k, irho)*sqrt(scratch(i, j, k, istrain))*d2wall(i&
&         , j, k)**2/rlv(i, j, k)
        delta = 375.0*vort*rlv(i, j, k)*w(i, j, k, itransition2)*d2wall(&
&         i, j, k)/(w(i, j, k, irho)*u**2)
        x4 = f_wake*exp(-((d2wall(i, j, k)/delta)**4))
        if (x4 .lt. 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2&
&           -1))**2) then
          x1 = 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2-1))&
&           **2
        else
          x1 = x4
        end if
        if (x1 .gt. 1.0) then
          f_theta_t = 1.0
        else
          f_theta_t = x1
        end if
        if (w(i, j, k, itransition2) .le. 1870.0) then
          re_theta_c = -3.96035 + 1.0120656*w(i, j, k, itransition2) + (&
&           -0.868230e-3)*w(i, j, k, itransition2)**2 + 0.696506e-6*w(i&
&           , j, k, itransition2)**3 + (-0.174105e-9)*w(i, j, k, &
&           itransition2)**4
        else
          re_theta_c = w(i, j, k, itransition2) - (593.11+0.482*(w(i, j&
&           , k, itransition2)-1870.0))
        end if
        f_reattach = exp(-((r_t/20.0)**4))
        if (0.0 .lt. re_s/(3.235*re_theta_c) - 1.0) then
          max1 = re_s/(3.235*re_theta_c) - 1.0
        else
          max1 = 0.0
        end if
        x2 = rlms1*max1*f_reattach
        if (x2 .gt. 2.0) then
          min1 = 2.0
        else
          min1 = x2
        end if
        gamma_sep = min1*f_theta_t
        if (w(i, j, k, itransition1) .lt. gamma_sep) then
          gamma_eff = gamma_sep
        else
          gamma_eff = w(i, j, k, itransition1)
        end if
! if gamma_eff = 1, the original sst should come out
        spk = gamma_eff*spk
        if (gamma_eff .lt. 0.1) then
          x3 = 0.1
        else
          x3 = gamma_eff
        end if
        if (x3 .gt. 1.0) then
          min2 = 1.0
        else
          min2 = x3
        end if
        sdk = min2*sdk
      end if
      scratch(i, j, k, idvt) = spk - sdk
      if (use2003sst) then
        scratch(i, j, k, idvt+1) = rsstgam*spk/rev(i, j, k) + two*t2*&
&         rsstsigw2*scratch(i, j, k, icd) - rsstbeta*w(i, j, k, itu2)**2
      else
        scratch(i, j, k, idvt+1) = rsstgam*ss + two*t2*rsstsigw2*scratch&
&         (i, j, k, icd) - rsstbeta*w(i, j, k, itu2)**2
      end if
! compute the source term jacobian. note that only the
! destruction terms are linearized to increase the diagonal
! dominance of the matrix. furthermore minus the source
! term jacobian is stored.

    end do
  end subroutine sstsource

!  differentiation of sstviscous in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *rev *w *rlv *scratch
!   with respect to varying inputs: *rev *w *rlv *scratch
!   rw status of diff variables: *rev:incr *w:incr *rlv:incr *scratch:in-out
!   plus diff mem management of: rev:in w:in rlv:in scratch:in
  subroutine sstviscous_fast_b()
    use blockpointers
    use constants
    use paramturb
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: t1, t2
    real(kind=realtype) :: t1d, t2d
    real(kind=realtype) :: rhoi
    real(kind=realtype) :: rhoid
    real(kind=realtype) :: voli, volmi, volpi
    real(kind=realtype) :: xm, ym, zm, xp, yp, zp, xa, ya, za
    real(kind=realtype) :: mulm, mulp, muem, muep
    real(kind=realtype) :: mulmd, mulpd, muemd, muepd
    real(kind=realtype) :: ttm, ttp
    real(kind=realtype) :: rsstsigkp1, rsstsigk, rsstsigkm1
    real(kind=realtype) :: rsstsigkp1d, rsstsigkd, rsstsigkm1d
    real(kind=realtype) :: rsstsigwp1, rsstsigw, rsstsigwm1
    real(kind=realtype) :: rsstsigwp1d, rsstsigwd, rsstsigwm1d
    real(kind=realtype) :: c1m, c1p, c10, c2m, c2p, c20
    real(kind=realtype) :: c1md, c1pd, c10d, c2md, c2pd, c20d
    real(kind=realtype) :: b1, b2, c1, c2, d1, d2
    real(kind=realtype) :: rblank
    intrinsic mod
    real(kind=realtype) :: temp
    real(kind=realtype) :: tempd
    integer :: branch
    if (associated(scratch)) then
      call pushreal8array(scratch, size(scratch, 1)*size(scratch, 2)*&
&                   size(scratch, 3)*size(scratch, 4))
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
    else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
    end if
!$fwd-of ii-loop 
!       advection and unsteady terms.
!
!
!       viscous terms in k-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for k-1,
! k and k+1.
! caution: f1 must be known in neighbouring cells (including halos!)
      t1 = scratch(i, j, k+1, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k-1, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dzeta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j, k-1)+rlv(i, j, k))
      mulp = half*(rlv(i, j, k+1)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i, j, k-1)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i, j, k+1)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      muem = half*(rsstsigwm1*rev(i, j, k-1)+rsstsigw*rev(i, j, k))
      muep = half*(rsstsigwp1*rev(i, j, k+1)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j, k-1&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j, k+1, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i, j, &
&       k-1, itu2) - c20*w(i, j, k, itu2) + c2p*w(i, j, k+1, itu2)
    end do
    if (associated(scratch)) then
      call pushreal8array(scratch, size(scratch, 1)*size(scratch, 2)*&
&                   size(scratch, 3)*size(scratch, 4))
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
    else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
    end if
!$fwd-of ii-loop 
!
!       viscous terms in j-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for j-1,
! j and j+1.
      t1 = scratch(i, j+1, k, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j-1, k, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/deta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j-1, k)+rlv(i, j, k))
      mulp = half*(rlv(i, j+1, k)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i, j-1, k)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i, j+1, k)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      muem = half*(rsstsigwm1*rev(i, j-1, k)+rsstsigw*rev(i, j, k))
      muep = half*(rsstsigwp1*rev(i, j+1, k)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j-1, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j+1, k, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i, j-1&
&       , k, itu2) - c20*w(i, j, k, itu2) + c2p*w(i, j+1, k, itu2)
    end do
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in xi-direction, i.e. along the
! line i = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for i-1,
! i and i+1.
      t1 = scratch(i+1, j, k, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i-1, j, k, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in xi-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in xi-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dxi^2 = d/dxi (d/dxi i+1/2 - d/dxi i-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dxi derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i-1, j, k)+rlv(i, j, k))
      mulp = half*(rlv(i+1, j, k)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i-1, j, k)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i+1, j, k)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      call pushreal8(muem)
      muem = half*(rsstsigwm1*rev(i-1, j, k)+rsstsigw*rev(i, j, k))
      call pushreal8(muep)
      muep = half*(rsstsigwp1*rev(i+1, j, k)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      c10d = -(w(i, j, k, itu1)*scratchd(i, j, k, idvt))
      c20d = -(w(i, j, k, itu2)*scratchd(i, j, k, idvt+1))
      c2md = w(i-1, j, k, itu2)*scratchd(i, j, k, idvt+1) + c20d
      wd(i-1, j, k, itu2) = wd(i-1, j, k, itu2) + c2m*scratchd(i, j, k, &
&       idvt+1)
      c2pd = w(i+1, j, k, itu2)*scratchd(i, j, k, idvt+1) + c20d
      wd(i+1, j, k, itu2) = wd(i+1, j, k, itu2) + c2p*scratchd(i, j, k, &
&       idvt+1)
      wd(i, j, k, itu2) = wd(i, j, k, itu2) - c20*scratchd(i, j, k, idvt&
&       +1)
      c1md = w(i-1, j, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i-1, j, k, itu1) = wd(i-1, j, k, itu1) + c1m*scratchd(i, j, k, &
&       idvt)
      c1pd = w(i+1, j, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i+1, j, k, itu1) = wd(i+1, j, k, itu1) + c1p*scratchd(i, j, k, &
&       idvt)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - c10*scratchd(i, j, k, idvt&
&       )
      tempd = ttp*c2pd
      mulpd = rhoi*tempd
      muepd = rhoi*tempd
      rhoid = (mulp+muep)*tempd
      tempd = ttm*c2md
      mulmd = rhoi*tempd
      muemd = rhoi*tempd
      rhoid = rhoid + (mulm+muem)*tempd
      call popreal8(muep)
      tempd = half*muepd
      rsstsigwp1d = rev(i+1, j, k)*tempd
      revd(i+1, j, k) = revd(i+1, j, k) + rsstsigwp1*tempd
      rsstsigwd = rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigw*tempd
      call popreal8(muem)
      tempd = half*muemd
      rsstsigwm1d = rev(i-1, j, k)*tempd
      revd(i-1, j, k) = revd(i-1, j, k) + rsstsigwm1*tempd
      rsstsigwd = rsstsigwd + rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigw*tempd
      tempd = ttp*c1pd
      mulpd = mulpd + rhoi*tempd
      muepd = rhoi*tempd
      rhoid = rhoid + (mulp+muep)*tempd
      tempd = ttm*c1md
      mulmd = mulmd + rhoi*tempd
      muemd = rhoi*tempd
      rhoid = rhoid + (mulm+muem)*tempd
      tempd = half*muepd
      rsstsigkp1d = rev(i+1, j, k)*tempd
      revd(i+1, j, k) = revd(i+1, j, k) + rsstsigkp1*tempd
      rsstsigkd = rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigk*tempd
      tempd = half*muemd
      rsstsigkm1d = rev(i-1, j, k)*tempd
      revd(i-1, j, k) = revd(i-1, j, k) + rsstsigkm1*tempd
      rsstsigkd = rsstsigkd + rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigk*tempd
      rlvd(i+1, j, k) = rlvd(i+1, j, k) + half*mulpd
      rlvd(i, j, k) = rlvd(i, j, k) + half*mulpd + half*mulmd
      rlvd(i-1, j, k) = rlvd(i-1, j, k) + half*mulmd
      temp = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp**2
      t2d = rsstsigw2*rsstsigwm1d + rsstsigk2*rsstsigkm1d
      t1d = rsstsigw1*rsstsigwm1d + rsstsigk1*rsstsigkm1d - t2d
      scratchd(i-1, j, k, if1sst) = scratchd(i-1, j, k, if1sst) + t1d
      t2d = rsstsigw2*rsstsigwd + rsstsigk2*rsstsigkd
      t1d = rsstsigw1*rsstsigwd + rsstsigk1*rsstsigkd - t2d
      scratchd(i, j, k, if1sst) = scratchd(i, j, k, if1sst) + t1d
      t2d = rsstsigw2*rsstsigwp1d + rsstsigk2*rsstsigkp1d
      t1d = rsstsigw1*rsstsigwp1d + rsstsigk1*rsstsigkp1d - t2d
      scratchd(i+1, j, k, if1sst) = scratchd(i+1, j, k, if1sst) + t1d
    end do
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
    if (branch .eq. 1) call popreal8array(scratch, size(scratch, 1)*size&
&                                   (scratch, 2)*size(scratch, 3)*size(&
&                                   scratch, 4))
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for j-1,
! j and j+1.
      t1 = scratch(i, j+1, k, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j-1, k, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/deta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j-1, k)+rlv(i, j, k))
      mulp = half*(rlv(i, j+1, k)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i, j-1, k)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i, j+1, k)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      call pushreal8(muem)
      muem = half*(rsstsigwm1*rev(i, j-1, k)+rsstsigw*rev(i, j, k))
      call pushreal8(muep)
      muep = half*(rsstsigwp1*rev(i, j+1, k)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      c10d = -(w(i, j, k, itu1)*scratchd(i, j, k, idvt))
      c20d = -(w(i, j, k, itu2)*scratchd(i, j, k, idvt+1))
      c2md = w(i, j-1, k, itu2)*scratchd(i, j, k, idvt+1) + c20d
      wd(i, j-1, k, itu2) = wd(i, j-1, k, itu2) + c2m*scratchd(i, j, k, &
&       idvt+1)
      c2pd = w(i, j+1, k, itu2)*scratchd(i, j, k, idvt+1) + c20d
      wd(i, j+1, k, itu2) = wd(i, j+1, k, itu2) + c2p*scratchd(i, j, k, &
&       idvt+1)
      wd(i, j, k, itu2) = wd(i, j, k, itu2) - c20*scratchd(i, j, k, idvt&
&       +1)
      c1md = w(i, j-1, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j-1, k, itu1) = wd(i, j-1, k, itu1) + c1m*scratchd(i, j, k, &
&       idvt)
      c1pd = w(i, j+1, k, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j+1, k, itu1) = wd(i, j+1, k, itu1) + c1p*scratchd(i, j, k, &
&       idvt)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - c10*scratchd(i, j, k, idvt&
&       )
      tempd = ttp*c2pd
      mulpd = rhoi*tempd
      muepd = rhoi*tempd
      rhoid = (mulp+muep)*tempd
      tempd = ttm*c2md
      mulmd = rhoi*tempd
      muemd = rhoi*tempd
      rhoid = rhoid + (mulm+muem)*tempd
      call popreal8(muep)
      tempd = half*muepd
      rsstsigwp1d = rev(i, j+1, k)*tempd
      revd(i, j+1, k) = revd(i, j+1, k) + rsstsigwp1*tempd
      rsstsigwd = rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigw*tempd
      call popreal8(muem)
      tempd = half*muemd
      rsstsigwm1d = rev(i, j-1, k)*tempd
      revd(i, j-1, k) = revd(i, j-1, k) + rsstsigwm1*tempd
      rsstsigwd = rsstsigwd + rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigw*tempd
      tempd = ttp*c1pd
      mulpd = mulpd + rhoi*tempd
      muepd = rhoi*tempd
      rhoid = rhoid + (mulp+muep)*tempd
      tempd = ttm*c1md
      mulmd = mulmd + rhoi*tempd
      muemd = rhoi*tempd
      rhoid = rhoid + (mulm+muem)*tempd
      tempd = half*muepd
      rsstsigkp1d = rev(i, j+1, k)*tempd
      revd(i, j+1, k) = revd(i, j+1, k) + rsstsigkp1*tempd
      rsstsigkd = rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigk*tempd
      tempd = half*muemd
      rsstsigkm1d = rev(i, j-1, k)*tempd
      revd(i, j-1, k) = revd(i, j-1, k) + rsstsigkm1*tempd
      rsstsigkd = rsstsigkd + rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigk*tempd
      rlvd(i, j+1, k) = rlvd(i, j+1, k) + half*mulpd
      rlvd(i, j, k) = rlvd(i, j, k) + half*mulpd + half*mulmd
      rlvd(i, j-1, k) = rlvd(i, j-1, k) + half*mulmd
      temp = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp**2
      t2d = rsstsigw2*rsstsigwm1d + rsstsigk2*rsstsigkm1d
      t1d = rsstsigw1*rsstsigwm1d + rsstsigk1*rsstsigkm1d - t2d
      scratchd(i, j-1, k, if1sst) = scratchd(i, j-1, k, if1sst) + t1d
      t2d = rsstsigw2*rsstsigwd + rsstsigk2*rsstsigkd
      t1d = rsstsigw1*rsstsigwd + rsstsigk1*rsstsigkd - t2d
      scratchd(i, j, k, if1sst) = scratchd(i, j, k, if1sst) + t1d
      t2d = rsstsigw2*rsstsigwp1d + rsstsigk2*rsstsigkp1d
      t1d = rsstsigw1*rsstsigwp1d + rsstsigk1*rsstsigkp1d - t2d
      scratchd(i, j+1, k, if1sst) = scratchd(i, j+1, k, if1sst) + t1d
    end do
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
    if (branch .eq. 1) call popreal8array(scratch, size(scratch, 1)*size&
&                                   (scratch, 2)*size(scratch, 3)*size(&
&                                   scratch, 4))
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for k-1,
! k and k+1.
! caution: f1 must be known in neighbouring cells (including halos!)
      t1 = scratch(i, j, k+1, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k-1, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dzeta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j, k-1)+rlv(i, j, k))
      mulp = half*(rlv(i, j, k+1)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i, j, k-1)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i, j, k+1)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      call pushreal8(muem)
      muem = half*(rsstsigwm1*rev(i, j, k-1)+rsstsigw*rev(i, j, k))
      call pushreal8(muep)
      muep = half*(rsstsigwp1*rev(i, j, k+1)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      c10d = -(w(i, j, k, itu1)*scratchd(i, j, k, idvt))
      c20d = -(w(i, j, k, itu2)*scratchd(i, j, k, idvt+1))
      c2md = w(i, j, k-1, itu2)*scratchd(i, j, k, idvt+1) + c20d
      wd(i, j, k-1, itu2) = wd(i, j, k-1, itu2) + c2m*scratchd(i, j, k, &
&       idvt+1)
      c2pd = w(i, j, k+1, itu2)*scratchd(i, j, k, idvt+1) + c20d
      wd(i, j, k+1, itu2) = wd(i, j, k+1, itu2) + c2p*scratchd(i, j, k, &
&       idvt+1)
      wd(i, j, k, itu2) = wd(i, j, k, itu2) - c20*scratchd(i, j, k, idvt&
&       +1)
      c1md = w(i, j, k-1, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j, k-1, itu1) = wd(i, j, k-1, itu1) + c1m*scratchd(i, j, k, &
&       idvt)
      c1pd = w(i, j, k+1, itu1)*scratchd(i, j, k, idvt) + c10d
      wd(i, j, k+1, itu1) = wd(i, j, k+1, itu1) + c1p*scratchd(i, j, k, &
&       idvt)
      wd(i, j, k, itu1) = wd(i, j, k, itu1) - c10*scratchd(i, j, k, idvt&
&       )
      tempd = ttp*c2pd
      mulpd = rhoi*tempd
      muepd = rhoi*tempd
      rhoid = (mulp+muep)*tempd
      tempd = ttm*c2md
      mulmd = rhoi*tempd
      muemd = rhoi*tempd
      rhoid = rhoid + (mulm+muem)*tempd
      call popreal8(muep)
      tempd = half*muepd
      rsstsigwp1d = rev(i, j, k+1)*tempd
      revd(i, j, k+1) = revd(i, j, k+1) + rsstsigwp1*tempd
      rsstsigwd = rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigw*tempd
      call popreal8(muem)
      tempd = half*muemd
      rsstsigwm1d = rev(i, j, k-1)*tempd
      revd(i, j, k-1) = revd(i, j, k-1) + rsstsigwm1*tempd
      rsstsigwd = rsstsigwd + rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigw*tempd
      tempd = ttp*c1pd
      mulpd = mulpd + rhoi*tempd
      muepd = rhoi*tempd
      rhoid = rhoid + (mulp+muep)*tempd
      tempd = ttm*c1md
      mulmd = mulmd + rhoi*tempd
      muemd = rhoi*tempd
      rhoid = rhoid + (mulm+muem)*tempd
      tempd = half*muepd
      rsstsigkp1d = rev(i, j, k+1)*tempd
      revd(i, j, k+1) = revd(i, j, k+1) + rsstsigkp1*tempd
      rsstsigkd = rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigk*tempd
      tempd = half*muemd
      rsstsigkm1d = rev(i, j, k-1)*tempd
      revd(i, j, k-1) = revd(i, j, k-1) + rsstsigkm1*tempd
      rsstsigkd = rsstsigkd + rev(i, j, k)*tempd
      revd(i, j, k) = revd(i, j, k) + rsstsigk*tempd
      rlvd(i, j, k+1) = rlvd(i, j, k+1) + half*mulpd
      rlvd(i, j, k) = rlvd(i, j, k) + half*mulpd + half*mulmd
      rlvd(i, j, k-1) = rlvd(i, j, k-1) + half*mulmd
      temp = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp**2
      t2d = rsstsigw2*rsstsigwm1d + rsstsigk2*rsstsigkm1d
      t1d = rsstsigw1*rsstsigwm1d + rsstsigk1*rsstsigkm1d - t2d
      scratchd(i, j, k-1, if1sst) = scratchd(i, j, k-1, if1sst) + t1d
      t2d = rsstsigw2*rsstsigwd + rsstsigk2*rsstsigkd
      t1d = rsstsigw1*rsstsigwd + rsstsigk1*rsstsigkd - t2d
      scratchd(i, j, k, if1sst) = scratchd(i, j, k, if1sst) + t1d
      t2d = rsstsigw2*rsstsigwp1d + rsstsigk2*rsstsigkp1d
      t1d = rsstsigw1*rsstsigwp1d + rsstsigk1*rsstsigkp1d - t2d
      scratchd(i, j, k+1, if1sst) = scratchd(i, j, k+1, if1sst) + t1d
    end do
  end subroutine sstviscous_fast_b

  subroutine sstviscous()
    use blockpointers
    use constants
    use paramturb
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: t1, t2
    real(kind=realtype) :: rhoi
    real(kind=realtype) :: voli, volmi, volpi
    real(kind=realtype) :: xm, ym, zm, xp, yp, zp, xa, ya, za
    real(kind=realtype) :: mulm, mulp, muem, muep
    real(kind=realtype) :: ttm, ttp
    real(kind=realtype) :: rsstsigkp1, rsstsigk, rsstsigkm1
    real(kind=realtype) :: rsstsigwp1, rsstsigw, rsstsigwm1
    real(kind=realtype) :: c1m, c1p, c10, c2m, c2p, c20
    real(kind=realtype) :: b1, b2, c1, c2, d1, d2
    real(kind=realtype) :: rblank
    intrinsic mod
!$ad ii-loop
!       advection and unsteady terms.
!
!
!       viscous terms in k-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for k-1,
! k and k+1.
! caution: f1 must be known in neighbouring cells (including halos!)
      t1 = scratch(i, j, k+1, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k-1, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dzeta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j, k-1)+rlv(i, j, k))
      mulp = half*(rlv(i, j, k+1)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i, j, k-1)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i, j, k+1)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      muem = half*(rsstsigwm1*rev(i, j, k-1)+rsstsigw*rev(i, j, k))
      muep = half*(rsstsigwp1*rev(i, j, k+1)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j, k-1&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j, k+1, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i, j, &
&       k-1, itu2) - c20*w(i, j, k, itu2) + c2p*w(i, j, k+1, itu2)
    end do
!$ad ii-loop
!
!       viscous terms in j-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for j-1,
! j and j+1.
      t1 = scratch(i, j+1, k, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j-1, k, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/deta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j-1, k)+rlv(i, j, k))
      mulp = half*(rlv(i, j+1, k)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i, j-1, k)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i, j+1, k)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      muem = half*(rsstsigwm1*rev(i, j-1, k)+rsstsigw*rev(i, j, k))
      muep = half*(rsstsigwp1*rev(i, j+1, k)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i, j-1, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i, j+1, k, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i, j-1&
&       , k, itu2) - c20*w(i, j, k, itu2) + c2p*w(i, j+1, k, itu2)
    end do
!$ad ii-loop
!
!       viscous terms in i-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in xi-direction, i.e. along the
! line i = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! compute the blended diffusion coefficients for i-1,
! i and i+1.
      t1 = scratch(i+1, j, k, if1sst)
      t2 = one - t1
      rsstsigkp1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwp1 = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i, j, k, if1sst)
      t2 = one - t1
      rsstsigk = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigw = t1*rsstsigw1 + t2*rsstsigw2
      t1 = scratch(i-1, j, k, if1sst)
      t2 = one - t1
      rsstsigkm1 = t1*rsstsigk1 + t2*rsstsigk2
      rsstsigwm1 = t1*rsstsigw1 + t2*rsstsigw2
! computation of the viscous terms in xi-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in xi-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dxi^2 = d/dxi (d/dxi i+1/2 - d/dxi i-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dxi derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the k-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i-1, j, k)+rlv(i, j, k))
      mulp = half*(rlv(i+1, j, k)+rlv(i, j, k))
      muem = half*(rsstsigkm1*rev(i-1, j, k)+rsstsigk*rev(i, j, k))
      muep = half*(rsstsigkp1*rev(i+1, j, k)+rsstsigk*rev(i, j, k))
      c1m = ttm*(mulm+muem)*rhoi
      c1p = ttp*(mulp+muep)*rhoi
      c10 = c1m + c1p
! and the omega term.
      muem = half*(rsstsigwm1*rev(i-1, j, k)+rsstsigw*rev(i, j, k))
      muep = half*(rsstsigwp1*rev(i+1, j, k)+rsstsigw*rev(i, j, k))
      c2m = ttm*(mulm+muem)*rhoi
      c2p = ttp*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, idvt) = scratch(i, j, k, idvt) + c1m*w(i-1, j, k&
&       , itu1) - c10*w(i, j, k, itu1) + c1p*w(i+1, j, k, itu1)
      scratch(i, j, k, idvt+1) = scratch(i, j, k, idvt+1) + c2m*w(i-1, j&
&       , k, itu2) - c20*w(i, j, k, itu2) + c2p*w(i+1, j, k, itu2)
    end do
  end subroutine sstviscous

!  differentiation of sstresscale in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *dw
!   with respect to varying inputs: *dw *scratch
!   rw status of diff variables: *dw:in-out *scratch:out
!   plus diff mem management of: dw:in scratch:in
  subroutine sstresscale_fast_b()
    use blockpointers
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
    if (associated(scratchd)) scratchd = 0.0_8
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      rblank = real(iblank(i, j, k), realtype)
      scratchd(i, j, k, idvt+1) = scratchd(i, j, k, idvt+1) - volref(i, &
&       j, k)*rblank*dwd(i, j, k, itu2)
      dwd(i, j, k, itu2) = 0.0_8
      scratchd(i, j, k, idvt) = scratchd(i, j, k, idvt) - volref(i, j, k&
&       )*rblank*dwd(i, j, k, itu1)
      dwd(i, j, k, itu1) = 0.0_8
    end do
  end subroutine sstresscale_fast_b

  subroutine sstresscale()
    use blockpointers
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
!$ad ii-loop
! multiply the residual by the volume and store this in dw; this
! is done for monitoring reasons only. the multiplication with the
! volume is present to be consistent with the flow residuals; also
! the negative value is taken, again to be consistent with the
! flow equations. also multiply by iblank so that no updates occur
! in holes or the overset boundary.
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      rblank = real(iblank(i, j, k), realtype)
      dw(i, j, k, itu1) = -(volref(i, j, k)*scratch(i, j, k, idvt)*&
&       rblank)
      dw(i, j, k, itu2) = -(volref(i, j, k)*scratch(i, j, k, idvt+1)*&
&       rblank)
    end do
  end subroutine sstresscale

!  differentiation of f1sst in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *w *rlv *scratch
!   with respect to varying inputs: *w *rlv *scratch
!   rw status of diff variables: *w:incr *rlv:incr *scratch:in-out
!   plus diff mem management of: w:in rlv:in scratch:in
  subroutine f1sst_fast_b()
!
!       f1sst computes the blending function f1 in both the owned
!       cells and the first layer of halo's. the result is stored in
!       scratch(:,:,:,if1sst). for the computation of f1 also the cross
!       diffusion term is needed. this is stored in scratch(:,:,:,icd) such
!       that it can be used in sstsolve later on.
!
    use constants
    use blockpointers
    use inputtimespectral
    use iteration
    use paramturb, only : rsstsigw2
    use inputphysics, only : use2003sst, transitionmodel
    use utils_fast_b, only : smoothmin, smoothmin_fast_b, smoothmax, &
&   smoothmax_fast_b
    use inputiteration, only : smoothsstphi
    use inputdiscretization, only : approxturb
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: sps, nn, mm, i, j, k, ii
    integer(kind=inttype) :: isize, ibeg, iend
    integer(kind=inttype) :: jsize, jbeg, jend
    integer(kind=inttype) :: ksize, kbeg, kend
    real(kind=realtype) :: t1, t2, arg1, myeps, f1, f3, ry
    real(kind=realtype) :: t1d, t2d, arg1d
    intrinsic mod
    intrinsic sqrt
    intrinsic max
    intrinsic tanh
    intrinsic exp
    real(kind=realtype) :: max1
    real(kind=realtype) :: max1d
    real(kind=realtype) :: max2
    real(kind=realtype) :: max2d
    real(kind=realtype) :: tmp
    real(kind=realtype) :: tmpd
    real(kind=realtype) :: tmp0
    real(kind=realtype) :: tmpd0
    real(kind=realtype) :: tmp1
    real(kind=realtype) :: tmpd1
    integer :: branch
    real(realtype) :: temp
    real(realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: temp2
    real(kind=realtype) :: temp3
    real(kind=realtype) :: temp4
    real(kind=realtype) :: tempd
    real(kind=realtype) :: temp5
    real(kind=realtype) :: tempd0
    integer :: ad_from
    integer :: ad_to
    integer :: ad_from0
    integer :: ad_to0
    integer :: ad_from1
    integer :: ad_to1
    integer :: ad_from2
    integer :: ad_to2
    integer :: ad_from3
    integer :: ad_to3
    integer :: ad_from4
    integer :: ad_to4
    integer :: ad_from5
    integer :: ad_to5
    integer :: ad_from6
    integer :: ad_to6
    integer :: ad_from7
    integer :: ad_to7
    integer :: ad_from8
    integer :: ad_to8
    integer :: ad_from9
    integer :: ad_to9
    integer :: ad_from10
    integer :: ad_to10
    myeps = 1e-10_realtype/two/rsstsigw2
    ibeg = 1
    jbeg = 1
    kbeg = 1
    iend = ie
    jend = je
    kend = ke
    do nn=1,nbocos
      select case  (bcfaceid(nn)) 
      case (imin) 
        call pushcontrol3b(5)
        ibeg = 2
      case (imax) 
        call pushcontrol3b(4)
        iend = il
      case (jmin) 
        call pushcontrol3b(3)
        jbeg = 2
      case (jmax) 
        call pushcontrol3b(2)
        jend = jl
      case (kmin) 
        call pushcontrol3b(1)
        kbeg = 2
      case (kmax) 
        call pushcontrol3b(0)
        kend = kl
      case default
        call pushcontrol3b(6)
      end select
    end do
! compute the blending function f1 for all owned cells.
    isize = iend - ibeg + 1
    jsize = jend - jbeg + 1
    ksize = kend - kbeg + 1
! loop over the boundary conditions to set f1 in the boundary
! halo's. a neumann boundary condition is used for all bc's.
bocos:do nn=1,nbocos
! determine the face on which this subface is located, loop
! over its range and copy f1. although the range may include
! indirect halo's which are not computed, this is no problem,
! because in sstsolve only direct halo's are used.
      select case  (bcfaceid(nn)) 
      case (imin) 
        ad_from0 = kcbeg(nn)
        do k=ad_from0,kcend(nn)
          ad_from = jcbeg(nn)
          j = jcend(nn) + 1
          call pushinteger4(j - 1)
          call pushinteger4(ad_from)
        end do
        call pushinteger4(k - 1)
        call pushinteger4(ad_from0)
        call pushcontrol3b(5)
      case (imax) 
        ad_from2 = kcbeg(nn)
!              ==========================================================
        do k=ad_from2,kcend(nn)
          ad_from1 = jcbeg(nn)
          j = jcend(nn) + 1
          call pushinteger4(j - 1)
          call pushinteger4(ad_from1)
        end do
        call pushinteger4(k - 1)
        call pushinteger4(ad_from2)
        call pushcontrol3b(4)
      case (jmin) 
        ad_from4 = kcbeg(nn)
!              ==========================================================
        do k=ad_from4,kcend(nn)
          ad_from3 = icbeg(nn)
          i = icend(nn) + 1
          call pushinteger4(i - 1)
          call pushinteger4(ad_from3)
        end do
        call pushinteger4(k - 1)
        call pushinteger4(ad_from4)
        call pushcontrol3b(3)
      case (jmax) 
        ad_from6 = kcbeg(nn)
!              ==========================================================
        do k=ad_from6,kcend(nn)
          ad_from5 = icbeg(nn)
          i = icend(nn) + 1
          call pushinteger4(i - 1)
          call pushinteger4(ad_from5)
        end do
        call pushinteger4(k - 1)
        call pushinteger4(ad_from6)
        call pushcontrol3b(2)
      case (kmin) 
        ad_from8 = jcbeg(nn)
!              ==========================================================
        do j=ad_from8,jcend(nn)
          ad_from7 = icbeg(nn)
          i = icend(nn) + 1
          call pushinteger4(i - 1)
          call pushinteger4(ad_from7)
        end do
        call pushinteger4(j - 1)
        call pushinteger4(ad_from8)
        call pushcontrol3b(1)
      case (kmax) 
        ad_from10 = jcbeg(nn)
!              ==========================================================
        do j=ad_from10,jcend(nn)
          ad_from9 = icbeg(nn)
          i = icend(nn) + 1
          call pushinteger4(i - 1)
          call pushinteger4(ad_from9)
        end do
        call pushinteger4(j - 1)
        call pushinteger4(ad_from10)
        call pushcontrol3b(0)
      case default
        call pushcontrol3b(6)
      end select
    end do bocos
    do nn=nbocos,1,-1
      call popcontrol3b(branch)
      if (branch .lt. 3) then
        if (branch .eq. 0) then
          call popinteger4(ad_from10)
          call popinteger4(ad_to10)
          do j=ad_to10,ad_from10,-1
            call popinteger4(ad_from9)
            call popinteger4(ad_to9)
            do i=ad_to9,ad_from9,-1
              tmpd1 = scratchd(i, j, ke, if1sst)
              scratchd(i, j, ke, if1sst) = 0.0_8
              scratchd(i, j, kl, if1sst) = scratchd(i, j, kl, if1sst) + &
&               tmpd1
            end do
          end do
        else if (branch .eq. 1) then
          call popinteger4(ad_from8)
          call popinteger4(ad_to8)
          do j=ad_to8,ad_from8,-1
            call popinteger4(ad_from7)
            call popinteger4(ad_to7)
            do i=ad_to7,ad_from7,-1
              scratchd(i, j, 2, if1sst) = scratchd(i, j, 2, if1sst) + &
&               scratchd(i, j, 1, if1sst)
              scratchd(i, j, 1, if1sst) = 0.0_8
            end do
          end do
        else
          call popinteger4(ad_from6)
          call popinteger4(ad_to6)
          do k=ad_to6,ad_from6,-1
            call popinteger4(ad_from5)
            call popinteger4(ad_to5)
            do i=ad_to5,ad_from5,-1
              tmpd0 = scratchd(i, je, k, if1sst)
              scratchd(i, je, k, if1sst) = 0.0_8
              scratchd(i, jl, k, if1sst) = scratchd(i, jl, k, if1sst) + &
&               tmpd0
            end do
          end do
        end if
      else if (branch .lt. 5) then
        if (branch .eq. 3) then
          call popinteger4(ad_from4)
          call popinteger4(ad_to4)
          do k=ad_to4,ad_from4,-1
            call popinteger4(ad_from3)
            call popinteger4(ad_to3)
            do i=ad_to3,ad_from3,-1
              scratchd(i, 2, k, if1sst) = scratchd(i, 2, k, if1sst) + &
&               scratchd(i, 1, k, if1sst)
              scratchd(i, 1, k, if1sst) = 0.0_8
            end do
          end do
        else
          call popinteger4(ad_from2)
          call popinteger4(ad_to2)
          do k=ad_to2,ad_from2,-1
            call popinteger4(ad_from1)
            call popinteger4(ad_to1)
            do j=ad_to1,ad_from1,-1
              tmpd = scratchd(ie, j, k, if1sst)
              scratchd(ie, j, k, if1sst) = 0.0_8
              scratchd(il, j, k, if1sst) = scratchd(il, j, k, if1sst) + &
&               tmpd
            end do
          end do
        end if
      else if (branch .eq. 5) then
        call popinteger4(ad_from0)
        call popinteger4(ad_to0)
        do k=ad_to0,ad_from0,-1
          call popinteger4(ad_from)
          call popinteger4(ad_to)
          do j=ad_to,ad_from,-1
            scratchd(2, j, k, if1sst) = scratchd(2, j, k, if1sst) + &
&             scratchd(1, j, k, if1sst)
            scratchd(1, j, k, if1sst) = 0.0_8
          end do
        end do
      end if
    end do
!$bwd-of ii-loop 
    do ii=0,isize*jsize*ksize-1
      i = mod(ii, isize) + ibeg
      j = mod(ii/isize, jsize) + jbeg
      k = ii/(isize*jsize) + kbeg
! if the turbulent kinetic energy falls below 0, this sqrt produces a nan. this presumably only happens if
! the dadi (for turbulence) solver is used. the ank solver should check and prevent this. since t1 is later
! max-ed with t2, we just set it to 0 if the turbulent kinetic energy is below 0
      if (w(i, j, k, itu1) .gt. 0) then
        t1 = sqrt(w(i, j, k, itu1))/(0.09_realtype*w(i, j, k, itu2)*&
&         d2wall(i, j, k))
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        t1 = 0_realtype
      end if
      t2 = 500.0_realtype*rlv(i, j, k)/(w(i, j, k, irho)*w(i, j, k, itu2&
&       )*d2wall(i, j, k)**2)
! 1e3
      call smoothmax(t1, t1, t2, smoothsstphi(4))
      if (use2003sst) then
        if (myeps/w(i, j, k, irho) .lt. scratch(i, j, k, icd)) then
          max1 = scratch(i, j, k, icd)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
          max1 = myeps/w(i, j, k, irho)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
        end if
        call pushreal8(t2)
        t2 = two*w(i, j, k, itu1)/(max1*d2wall(i, j, k)**2)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
      else
        if (eps .lt. scratch(i, j, k, icd)) then
          max2 = scratch(i, j, k, icd)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 0
        else
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
          max2 = eps
        end if
        call pushreal8(t2)
        t2 = two*w(i, j, k, itu1)/(max2*d2wall(i, j, k)**2)
myIntPtr = myIntPtr + 1
 myIntStack(myIntPtr) = 1
      end if
! 1e4
      call smoothmin(arg1, t1, t2, smoothsstphi(4))
      arg1d = 4*arg1**3*(1.0-tanh(arg1**4)**2)*scratchd(i, j, k, if1sst)
      scratchd(i, j, k, if1sst) = 0.0_8
      call smoothmin_fast_b(arg1, arg1d, t1, t1d, t2, t2d, smoothsstphi(&
&                     4))
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        call popreal8(t2)
        temp5 = d2wall(i, j, k)*d2wall(i, j, k)
        tempd = two*t2d/(temp5*max1)
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + tempd
        max1d = -(w(i, j, k, itu1)*tempd/max1)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) then
          scratchd(i, j, k, icd) = scratchd(i, j, k, icd) + max1d
        else
          temp5 = w(i, j, k, irho)
          wd(i, j, k, irho) = wd(i, j, k, irho) - myeps*max1d/temp5**2
        end if
      else
        call popreal8(t2)
        temp5 = d2wall(i, j, k)*d2wall(i, j, k)
        tempd = two*t2d/(temp5*max2)
        wd(i, j, k, itu1) = wd(i, j, k, itu1) + tempd
        max2d = -(w(i, j, k, itu1)*tempd/max2)
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
        if (branch .eq. 0) scratchd(i, j, k, icd) = scratchd(i, j, k, &
&           icd) + max2d
      end if
      call smoothmax_fast_b(t1, t1d, t1, t1d, t2, t2d, smoothsstphi(4))
      t1d = 0.0_8
      temp2 = w(i, j, k, itu2)
      temp1 = w(i, j, k, irho)
      temp3 = d2wall(i, j, k)*d2wall(i, j, k)
      temp4 = temp3*temp1*temp2
      tempd = 500.0_realtype*t2d/temp4
      rlvd(i, j, k) = rlvd(i, j, k) + tempd
      tempd0 = -(temp3*rlv(i, j, k)*tempd/temp4)
      wd(i, j, k, irho) = wd(i, j, k, irho) + temp2*tempd0
      wd(i, j, k, itu2) = wd(i, j, k, itu2) + temp1*tempd0
branch = myIntStack(myIntPtr)
 myIntPtr = myIntPtr - 1
      if (branch .eq. 0) then
        temp = 0.09_realtype*d2wall(i, j, k)
        temp0 = temp*w(i, j, k, itu2)
        temp1 = w(i, j, k, itu1)
        temp2 = sqrt(temp1)
        if (.not.temp1 .eq. 0.0_8) wd(i, j, k, itu1) = wd(i, j, k, itu1)&
&           + t1d/(2.0*temp2*temp0)
        wd(i, j, k, itu2) = wd(i, j, k, itu2) - temp*temp2*t1d/temp0**2
      end if
    end do
    do nn=nbocos,1,-1
      call popcontrol3b(branch)
    end do
  end subroutine f1sst_fast_b

  subroutine f1sst()
!
!       f1sst computes the blending function f1 in both the owned
!       cells and the first layer of halo's. the result is stored in
!       scratch(:,:,:,if1sst). for the computation of f1 also the cross
!       diffusion term is needed. this is stored in scratch(:,:,:,icd) such
!       that it can be used in sstsolve later on.
!
    use constants
    use blockpointers
    use inputtimespectral
    use iteration
    use paramturb, only : rsstsigw2
    use inputphysics, only : use2003sst, transitionmodel
    use utils_fast_b, only : smoothmin, smoothmax
    use inputiteration, only : smoothsstphi
    use inputdiscretization, only : approxturb
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: sps, nn, mm, i, j, k, ii
    integer(kind=inttype) :: isize, ibeg, iend
    integer(kind=inttype) :: jsize, jbeg, jend
    integer(kind=inttype) :: ksize, kbeg, kend
    real(kind=realtype) :: t1, t2, arg1, myeps, f1, f3, ry
    intrinsic mod
    intrinsic sqrt
    intrinsic max
    intrinsic tanh
    intrinsic exp
    real(kind=realtype) :: max1
    real(kind=realtype) :: max2
    myeps = 1e-10_realtype/two/rsstsigw2
    ibeg = 1
    jbeg = 1
    kbeg = 1
    iend = ie
    jend = je
    kend = ke
    do nn=1,nbocos
      select case  (bcfaceid(nn)) 
      case (imin) 
        ibeg = 2
      case (imax) 
        iend = il
      case (jmin) 
        jbeg = 2
      case (jmax) 
        jend = jl
      case (kmin) 
        kbeg = 2
      case (kmax) 
        kend = kl
      end select
    end do
! compute the blending function f1 for all owned cells.
    isize = iend - ibeg + 1
    jsize = jend - jbeg + 1
    ksize = kend - kbeg + 1
!$ad ii-loop
    do ii=0,isize*jsize*ksize-1
      i = mod(ii, isize) + ibeg
      j = mod(ii/isize, jsize) + jbeg
      k = ii/(isize*jsize) + kbeg
! if the turbulent kinetic energy falls below 0, this sqrt produces a nan. this presumably only happens if
! the dadi (for turbulence) solver is used. the ank solver should check and prevent this. since t1 is later
! max-ed with t2, we just set it to 0 if the turbulent kinetic energy is below 0
      if (w(i, j, k, itu1) .gt. 0) then
        t1 = sqrt(w(i, j, k, itu1))/(0.09_realtype*w(i, j, k, itu2)*&
&         d2wall(i, j, k))
      else
        t1 = 0_realtype
      end if
      t2 = 500.0_realtype*rlv(i, j, k)/(w(i, j, k, irho)*w(i, j, k, itu2&
&       )*d2wall(i, j, k)**2)
! 1e3
      call smoothmax(t1, t1, t2, smoothsstphi(4))
      if (use2003sst) then
        if (myeps/w(i, j, k, irho) .lt. scratch(i, j, k, icd)) then
          max1 = scratch(i, j, k, icd)
        else
          max1 = myeps/w(i, j, k, irho)
        end if
        t2 = two*w(i, j, k, itu1)/(max1*d2wall(i, j, k)**2)
      else
        if (eps .lt. scratch(i, j, k, icd)) then
          max2 = scratch(i, j, k, icd)
        else
          max2 = eps
        end if
        t2 = two*w(i, j, k, itu1)/(max2*d2wall(i, j, k)**2)
      end if
! 1e4
      call smoothmin(arg1, t1, t2, smoothsstphi(4))
      f1 = tanh(arg1**4)
      if (transitionmodel .eq. gammaretheta) then
        ry = w(i, j, k, irho)*d2wall(i, j, k)*sqrt(w(i, j, k, itu1))/rlv&
&         (i, j, k)
        f3 = exp(-((ry/120.0)**8))
        if (f1 .lt. f3) then
          f1 = f3
        else
          f1 = f1
        end if
      end if
! scratch(i, j, k, if1sst) = 1.0_realtype
      scratch(i, j, k, if1sst) = tanh(arg1**4)
    end do
! loop over the boundary conditions to set f1 in the boundary
! halo's. a neumann boundary condition is used for all bc's.
bocos:do nn=1,nbocos
! determine the face on which this subface is located, loop
! over its range and copy f1. although the range may include
! indirect halo's which are not computed, this is no problem,
! because in sstsolve only direct halo's are used.
      select case  (bcfaceid(nn)) 
      case (imin) 
        do k=kcbeg(nn),kcend(nn)
          do j=jcbeg(nn),jcend(nn)
            scratch(1, j, k, if1sst) = scratch(2, j, k, if1sst)
          end do
        end do
      case (imax) 
!              ==========================================================
        do k=kcbeg(nn),kcend(nn)
          do j=jcbeg(nn),jcend(nn)
            scratch(ie, j, k, if1sst) = scratch(il, j, k, if1sst)
          end do
        end do
      case (jmin) 
!              ==========================================================
        do k=kcbeg(nn),kcend(nn)
          do i=icbeg(nn),icend(nn)
            scratch(i, 1, k, if1sst) = scratch(i, 2, k, if1sst)
          end do
        end do
      case (jmax) 
!              ==========================================================
        do k=kcbeg(nn),kcend(nn)
          do i=icbeg(nn),icend(nn)
            scratch(i, je, k, if1sst) = scratch(i, jl, k, if1sst)
          end do
        end do
      case (kmin) 
!              ==========================================================
        do j=jcbeg(nn),jcend(nn)
          do i=icbeg(nn),icend(nn)
            scratch(i, j, 1, if1sst) = scratch(i, j, 2, if1sst)
          end do
        end do
      case (kmax) 
!              ==========================================================
        do j=jcbeg(nn),jcend(nn)
          do i=icbeg(nn),icend(nn)
            scratch(i, j, ke, if1sst) = scratch(i, j, kl, if1sst)
          end do
        end do
      end select
    end do bocos
  end subroutine f1sst

end module sst_fast_b

