!        generated by tapenade     (inria, ecuador team)
!  tapenade 3.16 (develop) - 22 aug 2023 15:51
!
module gammarethetamodel_b
  use constants
  implicit none

contains
!  differentiation of solve_local_re_thetat_eq in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *w *rlv *vol *si *sj *sk re_thetat_eq
!   with respect to varying inputs: *w *rlv *vol *si *sj *sk re_thetat_eq
!   rw status of diff variables: *w:incr *rlv:incr *vol:incr *si:incr
!                *sj:incr *sk:incr re_thetat_eq:in-zero
!   plus diff mem management of: w:in rlv:in vol:in si:in sj:in
!                sk:in
  subroutine solve_local_re_thetat_eq_b(re_thetat_eq, re_thetat_eqd, i, &
&   j, k)
    use blockpointers
    use constants
    use paramturb
    implicit none
! input/output variables
    integer(kind=inttype), intent(in) :: i, j, k
    real(kind=realtype) :: re_thetat_eq
    real(kind=realtype) :: re_thetat_eqd
! local variables
    real(kind=realtype) :: u, u_inv, fact, du_dx, du_dy, du_dz, du_ds, &
&   tu, f1, f2, f3, f
    real(kind=realtype) :: ud, u_invd, factd, du_dxd, du_dyd, du_dzd, &
&   du_dsd, tud, fd
    real(kind=realtype) :: dudx, dudy, dudz, dvdx, dvdy, dvdz, dwdx, &
&   dwdy, dwdz
    real(kind=realtype) :: dudxd, dudyd, dudzd, dvdxd, dvdyd, dvdzd, &
&   dwdxd, dwdyd, dwdzd
    real(kind=realtype) :: lambda, thetat, residum, thetat_old, &
&   residum_old, thetat_new
    real(kind=realtype) :: lambdad, thetatd, residumd, thetat_oldd, &
&   residum_oldd, thetat_newd
    real(kind=realtype) :: re_thetat_eq_1, re_thetat_eq_2
    real(kind=realtype) :: re_thetat_eq_1d, re_thetat_eq_2d
    integer(kind=inttype) :: n
    intrinsic sqrt
    intrinsic max
    intrinsic min
    intrinsic exp
    intrinsic abs
    real(kind=realtype) :: x1
    real(kind=realtype) :: x1d
    real(kind=realtype) :: x2
    real(kind=realtype) :: x2d
    real(kind=realtype) :: abs0
    real(kind=realtype) :: abs1
    real(kind=realtype) :: temp
    real(kind=realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: temp2
    real(kind=realtype) :: tempd
    real(kind=realtype) :: temp3
    real(kind=realtype) :: temp4
    real(kind=realtype) :: temp5
    real(kind=realtype) :: temp6
    real(kind=realtype) :: temp7
    real(kind=realtype) :: temp8
    real(kind=realtype) :: temp9
    real(kind=realtype) :: temp10
    real(kind=realtype) :: temp11
    real(kind=realtype) :: tempd0
    real(kind=realtype) :: tempd1
    real(kind=realtype) :: tempd2
    real(kind=realtype) :: tempd3
    integer :: branch
    integer :: ad_count
    integer :: i0
    u = sqrt(w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 + w(i, j, k, ivz)**&
&     2)
    u_inv = 1.0/u
! compute the gradient of u in the cell center. use is made
! of the fact that the surrounding normals sum up to zero,
! such that the cell i,j,k does not give a contribution.
! since the gradient is scaled by a factor of 2*vol, we need to account for that
    fact = 1.0/(vol(i, j, k)*2.0)
    dudx = (w(i+1, j, k, ivx)*si(i, j, k, 1)-w(i-1, j, k, ivx)*si(i-1, j&
&     , k, 1)+w(i, j+1, k, ivx)*sj(i, j, k, 1)-w(i, j-1, k, ivx)*sj(i, j&
&     -1, k, 1)+w(i, j, k+1, ivx)*sk(i, j, k, 1)-w(i, j, k-1, ivx)*sk(i&
&     , j, k-1, 1))*fact
    dudy = (w(i+1, j, k, ivx)*si(i, j, k, 2)-w(i-1, j, k, ivx)*si(i-1, j&
&     , k, 2)+w(i, j+1, k, ivx)*sj(i, j, k, 2)-w(i, j-1, k, ivx)*sj(i, j&
&     -1, k, 2)+w(i, j, k+1, ivx)*sk(i, j, k, 2)-w(i, j, k-1, ivx)*sk(i&
&     , j, k-1, 2))*fact
    dudz = (w(i+1, j, k, ivx)*si(i, j, k, 3)-w(i-1, j, k, ivx)*si(i-1, j&
&     , k, 3)+w(i, j+1, k, ivx)*sj(i, j, k, 3)-w(i, j-1, k, ivx)*sj(i, j&
&     -1, k, 3)+w(i, j, k+1, ivx)*sk(i, j, k, 3)-w(i, j, k-1, ivx)*sk(i&
&     , j, k-1, 3))*fact
! idem for the gradient of v.
    dvdx = (w(i+1, j, k, ivy)*si(i, j, k, 1)-w(i-1, j, k, ivy)*si(i-1, j&
&     , k, 1)+w(i, j+1, k, ivy)*sj(i, j, k, 1)-w(i, j-1, k, ivy)*sj(i, j&
&     -1, k, 1)+w(i, j, k+1, ivy)*sk(i, j, k, 1)-w(i, j, k-1, ivy)*sk(i&
&     , j, k-1, 1))*fact
    dvdy = (w(i+1, j, k, ivy)*si(i, j, k, 2)-w(i-1, j, k, ivy)*si(i-1, j&
&     , k, 2)+w(i, j+1, k, ivy)*sj(i, j, k, 2)-w(i, j-1, k, ivy)*sj(i, j&
&     -1, k, 2)+w(i, j, k+1, ivy)*sk(i, j, k, 2)-w(i, j, k-1, ivy)*sk(i&
&     , j, k-1, 2))*fact
    dvdz = (w(i+1, j, k, ivy)*si(i, j, k, 3)-w(i-1, j, k, ivy)*si(i-1, j&
&     , k, 3)+w(i, j+1, k, ivy)*sj(i, j, k, 3)-w(i, j-1, k, ivy)*sj(i, j&
&     -1, k, 3)+w(i, j, k+1, ivy)*sk(i, j, k, 3)-w(i, j, k-1, ivy)*sk(i&
&     , j, k-1, 3))*fact
! and for the gradient of w.
    dwdx = (w(i+1, j, k, ivz)*si(i, j, k, 1)-w(i-1, j, k, ivz)*si(i-1, j&
&     , k, 1)+w(i, j+1, k, ivz)*sj(i, j, k, 1)-w(i, j-1, k, ivz)*sj(i, j&
&     -1, k, 1)+w(i, j, k+1, ivz)*sk(i, j, k, 1)-w(i, j, k-1, ivz)*sk(i&
&     , j, k-1, 1))*fact
    dwdy = (w(i+1, j, k, ivz)*si(i, j, k, 2)-w(i-1, j, k, ivz)*si(i-1, j&
&     , k, 2)+w(i, j+1, k, ivz)*sj(i, j, k, 2)-w(i, j-1, k, ivz)*sj(i, j&
&     -1, k, 2)+w(i, j, k+1, ivz)*sk(i, j, k, 2)-w(i, j, k-1, ivz)*sk(i&
&     , j, k-1, 2))*fact
    dwdz = (w(i+1, j, k, ivz)*si(i, j, k, 3)-w(i-1, j, k, ivz)*si(i-1, j&
&     , k, 3)+w(i, j+1, k, ivz)*sj(i, j, k, 3)-w(i, j-1, k, ivz)*sj(i, j&
&     -1, k, 3)+w(i, j, k+1, ivz)*sk(i, j, k, 3)-w(i, j, k-1, ivz)*sk(i&
&     , j, k-1, 3))*fact
    du_dx = u_inv*(w(i, j, k, ivx)*dudx+w(i, j, k, ivy)*dudy+w(i, j, k, &
&     ivz)*dudz)
    du_dy = u_inv*(w(i, j, k, ivx)*dvdx+w(i, j, k, ivy)*dvdy+w(i, j, k, &
&     ivz)*dvdz)
    du_dz = u_inv*(w(i, j, k, ivx)*dwdx+w(i, j, k, ivy)*dwdy+w(i, j, k, &
&     ivz)*dwdz)
    du_ds = w(i, j, k, ivx)/u*du_dx + w(i, j, k, ivy)/u*du_dy + w(i, j, &
&     k, ivz)/u*du_dz
    tu = 100.0*sqrt(2*w(i, j, k, itu1)/3)/u
    if (tu .lt. 0.027) then
      tu = 0.027
      call pushcontrol1b(0)
    else
      call pushcontrol1b(1)
      tu = tu
    end if
! now we need to solve for theta through newton's method. the number of iterations is hard-coded so tapenade is 
! able to differentiate it
    thetat = 0.01
    ad_count = 1
    do n=1,10
      call pushreal8(lambda)
      lambda = w(i, j, k, irho)*thetat**2/rlv(i, j, k)*du_ds
      if (lambda .gt. 0.1) then
        x1 = 0.1
        call pushcontrol1b(0)
      else
        x1 = lambda
        call pushcontrol1b(1)
      end if
      if (x1 .lt. -0.1) then
        lambda = -0.1
        call pushcontrol1b(0)
      else
        lambda = x1
        call pushcontrol1b(1)
      end if
! compute f function
      if (lambda .le. 1.0e-9) then
        call pushreal8(f)
        f = 1.0 + (12.986*lambda+123.66*lambda**2+405.689*lambda**3)*exp&
&         (-((tu/1.5)**1.5))
        call pushcontrol1b(0)
      else
        call pushreal8(f)
        f = 1.0 + 0.275*(1.0-exp(-(35.0*lambda)))*exp(-(tu/0.5))
        call pushcontrol1b(1)
      end if
      if (tu .gt. 1.3) then
        re_thetat_eq_1 = 331.50*(tu-0.5658)**(-0.671)*f
        call pushcontrol1b(1)
      else
        re_thetat_eq_1 = (1173.51-589.428*tu+0.2196*tu**(-2))*f
        call pushcontrol1b(0)
      end if
      re_thetat_eq_2 = w(i, j, k, irho)*u*thetat/rlv(i, j, k)
! residum which should go to 0
      call pushreal8(residum)
      residum = re_thetat_eq_1 - re_thetat_eq_2
      if (residum .ge. 0.) then
        abs0 = residum
      else
        abs0 = -residum
      end if
! exit if converged
      if (abs0 .lt. 1e-9) then
        goto 100
      else
! apply the secant method update
        if (n .gt. 1) then
          if (residum - residum_old .ge. 0.) then
            abs1 = residum - residum_old
          else
            abs1 = -(residum-residum_old)
          end if
          if (abs1 .gt. 1.0e-12) then
            thetat_new = thetat - residum*(thetat_old-thetat)/(&
&             residum_old-residum)
            call pushcontrol1b(0)
          else
            goto 110
          end if
        else
! initial step
          thetat_new = 0.5*thetat
          call pushcontrol1b(1)
        end if
! update values for next iteration
        call pushreal8(thetat_old)
        thetat_old = thetat
        call pushreal8(residum_old)
        residum_old = residum
        call pushreal8(thetat)
        thetat = thetat_new
        ad_count = ad_count + 1
      end if
    end do
    call pushcontrol2b(0)
    call pushinteger4(ad_count)
    call pushcontrol1b(0)
    goto 120
 100 call pushcontrol2b(1)
    call pushinteger4(ad_count)
    call pushcontrol1b(0)
    goto 120
 110 call pushcontrol2b(2)
    call pushinteger4(ad_count)
    call pushcontrol1b(1)
 120 if (re_thetat_eq_1 .lt. 20.0) then
      x2 = 20.0
      call pushcontrol1b(0)
    else
      x2 = re_thetat_eq_1
      call pushcontrol1b(1)
    end if
    if (x2 .gt. 1.0e10) then
      x2d = 0.0_8
    else
      x2d = re_thetat_eqd
    end if
    call popcontrol1b(branch)
    if (branch .eq. 0) then
      re_thetat_eq_1d = 0.0_8
    else
      re_thetat_eq_1d = x2d
    end if
    call popcontrol1b(branch)
    call popinteger4(ad_count)
    do 130 i0=1,ad_count
      if (i0 .eq. 1) then
        call popcontrol2b(branch)
        if (branch .eq. 0) then
          tud = 0.0_8
          thetat_oldd = 0.0_8
          ud = 0.0_8
          du_dsd = 0.0_8
          residum_oldd = 0.0_8
          thetatd = 0.0_8
          goto 130
        else if (branch .eq. 1) then
          tud = 0.0_8
          thetat_oldd = 0.0_8
          ud = 0.0_8
          du_dsd = 0.0_8
          residum_oldd = 0.0_8
          residumd = 0.0_8
          thetatd = 0.0_8
        else
          tud = 0.0_8
          thetat_oldd = 0.0_8
          ud = 0.0_8
          du_dsd = 0.0_8
          residum_oldd = 0.0_8
          residumd = 0.0_8
          thetatd = 0.0_8
        end if
      else
        call popreal8(thetat)
        thetat_newd = thetatd
        call popreal8(residum_old)
        residumd = residum_oldd
        call popreal8(thetat_old)
        thetatd = thetat_oldd
        call popcontrol1b(branch)
        if (branch .eq. 0) then
          tempd0 = -(thetat_newd/(residum_old-residum))
          tempd2 = -(residum*(thetat_old-thetat)*tempd0/(residum_old-&
&           residum))
          thetatd = thetatd + thetat_newd - residum*tempd0
          residumd = residumd + (thetat_old-thetat)*tempd0 - tempd2
          thetat_oldd = residum*tempd0
          residum_oldd = tempd2
        else
          thetatd = thetatd + 0.5*thetat_newd
          thetat_oldd = 0.0_8
          residum_oldd = 0.0_8
        end if
      end if
      call popreal8(residum)
      re_thetat_eq_1d = re_thetat_eq_1d + residumd
      re_thetat_eq_2d = -residumd
      temp11 = u*thetat/rlv(i, j, k)
      wd(i, j, k, irho) = wd(i, j, k, irho) + temp11*re_thetat_eq_2d
      tempd0 = w(i, j, k, irho)*re_thetat_eq_2d/rlv(i, j, k)
      ud = ud + thetat*tempd0
      thetatd = thetatd + u*tempd0
      rlvd(i, j, k) = rlvd(i, j, k) - temp11*tempd0
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        temp11 = 0.2196/(tu*tu)
        tud = tud - (2*temp11*f/tu+589.428*f)*re_thetat_eq_1d
        fd = (temp11-589.428*tu+1173.51)*re_thetat_eq_1d
      else
        tud = tud - 0.671*(tu-0.5658)**(-1.671)*f*331.50*re_thetat_eq_1d
        fd = (tu-0.5658)**(-0.671)*331.50*re_thetat_eq_1d
      end if
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        call popreal8(f)
        temp11 = -((tu/1.5)**1.5)
        tempd2 = exp(temp11)*fd
        tud = tud - (tu/1.5)**0.5*exp(temp11)*(12.986*lambda+123.66*&
&         lambda**2+405.689*lambda**3)*fd
        lambdad = (2*lambda*123.66+3*lambda**2*405.689+12.986)*tempd2
      else
        call popreal8(f)
        lambdad = 35.0*exp(-(35.0*lambda))*exp(-(tu/0.5))*0.275*fd
        tud = tud - exp(-(tu/0.5))*(1.0-exp(-(35.0*lambda)))*0.275*fd/&
&         0.5
      end if
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        x1d = 0.0_8
      else
        x1d = lambdad
      end if
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        lambdad = 0.0_8
      else
        lambdad = x1d
      end if
      call popreal8(lambda)
      temp11 = w(i, j, k, irho)/rlv(i, j, k)
      tempd0 = thetat**2*du_ds*lambdad/rlv(i, j, k)
      thetatd = thetatd + 2*thetat*du_ds*temp11*lambdad
      du_dsd = du_dsd + thetat**2*temp11*lambdad
      wd(i, j, k, irho) = wd(i, j, k, irho) + tempd0
      rlvd(i, j, k) = rlvd(i, j, k) - temp11*tempd0
      re_thetat_eq_1d = 0.0_8
 130 continue
    call popcontrol1b(branch)
    if (branch .eq. 0) tud = 0.0_8
    temp10 = 2*w(i, j, k, itu1)/3
    temp9 = sqrt(temp10)
    tempd0 = 100.0*tud/u
    if (.not.temp10 .eq. 0.0_8) wd(i, j, k, itu1) = wd(i, j, k, itu1) + &
&       2*tempd0/(3*2.0*temp9)
    ud = ud - temp9*tempd0/u
    wd(i, j, k, ivx) = wd(i, j, k, ivx) + du_dx*du_dsd/u
    tempd0 = w(i, j, k, ivx)*du_dsd/u
    wd(i, j, k, ivy) = wd(i, j, k, ivy) + du_dy*du_dsd/u
    tempd2 = w(i, j, k, ivy)*du_dsd/u
    wd(i, j, k, ivz) = wd(i, j, k, ivz) + du_dz*du_dsd/u
    tempd3 = w(i, j, k, ivz)*du_dsd/u
    du_dzd = tempd3
    du_dyd = tempd2
    du_dxd = tempd0
    temp11 = w(i, j, k, ivz)
    temp10 = w(i, j, k, ivy)
    temp9 = w(i, j, k, ivx)
    u_invd = (temp9*dwdx+temp10*dwdy+temp11*dwdz)*du_dzd
    tempd1 = u_inv*du_dzd
    wd(i, j, k, ivx) = wd(i, j, k, ivx) + dwdx*tempd1
    dwdxd = temp9*tempd1
    wd(i, j, k, ivy) = wd(i, j, k, ivy) + dwdy*tempd1
    dwdyd = temp10*tempd1
    wd(i, j, k, ivz) = wd(i, j, k, ivz) + dwdz*tempd1
    dwdzd = temp11*tempd1
    temp11 = w(i, j, k, ivz)
    temp10 = w(i, j, k, ivy)
    temp9 = w(i, j, k, ivx)
    u_invd = u_invd + (temp9*dvdx+temp10*dvdy+temp11*dvdz)*du_dyd
    tempd1 = u_inv*du_dyd
    wd(i, j, k, ivx) = wd(i, j, k, ivx) + dvdx*tempd1
    dvdxd = temp9*tempd1
    wd(i, j, k, ivy) = wd(i, j, k, ivy) + dvdy*tempd1
    dvdyd = temp10*tempd1
    wd(i, j, k, ivz) = wd(i, j, k, ivz) + dvdz*tempd1
    dvdzd = temp11*tempd1
    temp11 = w(i, j, k, ivz)
    temp10 = w(i, j, k, ivy)
    temp9 = w(i, j, k, ivx)
    u_invd = u_invd + (temp9*dudx+temp10*dudy+temp11*dudz)*du_dxd
    ud = ud - du_dz*tempd3/u - du_dy*tempd2/u - du_dx*tempd0/u - u_invd/&
&     u**2
    tempd1 = u_inv*du_dxd
    wd(i, j, k, ivx) = wd(i, j, k, ivx) + dudx*tempd1
    dudxd = temp9*tempd1
    wd(i, j, k, ivy) = wd(i, j, k, ivy) + dudy*tempd1
    dudyd = temp10*tempd1
    wd(i, j, k, ivz) = wd(i, j, k, ivz) + dudz*tempd1
    dudzd = temp11*tempd1
    temp10 = si(i, j, k, 3)
    temp9 = w(i+1, j, k, ivz)
    temp8 = si(i-1, j, k, 3)
    temp7 = w(i-1, j, k, ivz)
    temp6 = sj(i, j, k, 3)
    temp5 = w(i, j+1, k, ivz)
    temp4 = sk(i, j, k, 3)
    temp3 = w(i, j, k+1, ivz)
    temp2 = sj(i, j-1, k, 3)
    temp1 = w(i, j-1, k, ivz)
    temp0 = sk(i, j, k-1, 3)
    temp = w(i, j, k-1, ivz)
    tempd0 = fact*dwdzd
    factd = (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-temp1*&
&     temp2-temp*temp0)*dwdzd
    wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + temp10*tempd0
    sid(i, j, k, 3) = sid(i, j, k, 3) + temp9*tempd0
    wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) - temp8*tempd0
    sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - temp7*tempd0
    wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + temp6*tempd0
    sjd(i, j, k, 3) = sjd(i, j, k, 3) + temp5*tempd0
    wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + temp4*tempd0
    skd(i, j, k, 3) = skd(i, j, k, 3) + temp3*tempd0
    wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) - temp2*tempd0
    sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - temp1*tempd0
    wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) - temp0*tempd0
    skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - temp*tempd0
    temp10 = si(i, j, k, 2)
    temp9 = w(i+1, j, k, ivz)
    temp8 = si(i-1, j, k, 2)
    temp7 = w(i-1, j, k, ivz)
    temp6 = sj(i, j, k, 2)
    temp5 = w(i, j+1, k, ivz)
    temp4 = sk(i, j, k, 2)
    temp3 = w(i, j, k+1, ivz)
    temp2 = sj(i, j-1, k, 2)
    temp1 = w(i, j-1, k, ivz)
    temp0 = sk(i, j, k-1, 2)
    temp = w(i, j, k-1, ivz)
    tempd0 = fact*dwdyd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dwdyd
    wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + temp10*tempd0
    sid(i, j, k, 2) = sid(i, j, k, 2) + temp9*tempd0
    wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) - temp8*tempd0
    sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - temp7*tempd0
    wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + temp6*tempd0
    sjd(i, j, k, 2) = sjd(i, j, k, 2) + temp5*tempd0
    wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + temp4*tempd0
    skd(i, j, k, 2) = skd(i, j, k, 2) + temp3*tempd0
    wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) - temp2*tempd0
    sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - temp1*tempd0
    wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) - temp0*tempd0
    skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - temp*tempd0
    temp10 = si(i, j, k, 1)
    temp9 = w(i+1, j, k, ivz)
    temp8 = si(i-1, j, k, 1)
    temp7 = w(i-1, j, k, ivz)
    temp6 = sj(i, j, k, 1)
    temp5 = w(i, j+1, k, ivz)
    temp4 = sk(i, j, k, 1)
    temp3 = w(i, j, k+1, ivz)
    temp2 = sj(i, j-1, k, 1)
    temp1 = w(i, j-1, k, ivz)
    temp0 = sk(i, j, k-1, 1)
    temp = w(i, j, k-1, ivz)
    tempd0 = fact*dwdxd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dwdxd
    wd(i+1, j, k, ivz) = wd(i+1, j, k, ivz) + temp10*tempd0
    sid(i, j, k, 1) = sid(i, j, k, 1) + temp9*tempd0
    wd(i-1, j, k, ivz) = wd(i-1, j, k, ivz) - temp8*tempd0
    sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - temp7*tempd0
    wd(i, j+1, k, ivz) = wd(i, j+1, k, ivz) + temp6*tempd0
    sjd(i, j, k, 1) = sjd(i, j, k, 1) + temp5*tempd0
    wd(i, j, k+1, ivz) = wd(i, j, k+1, ivz) + temp4*tempd0
    skd(i, j, k, 1) = skd(i, j, k, 1) + temp3*tempd0
    wd(i, j-1, k, ivz) = wd(i, j-1, k, ivz) - temp2*tempd0
    sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - temp1*tempd0
    wd(i, j, k-1, ivz) = wd(i, j, k-1, ivz) - temp0*tempd0
    skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - temp*tempd0
    temp10 = si(i, j, k, 3)
    temp9 = w(i+1, j, k, ivy)
    temp8 = si(i-1, j, k, 3)
    temp7 = w(i-1, j, k, ivy)
    temp6 = sj(i, j, k, 3)
    temp5 = w(i, j+1, k, ivy)
    temp4 = sk(i, j, k, 3)
    temp3 = w(i, j, k+1, ivy)
    temp2 = sj(i, j-1, k, 3)
    temp1 = w(i, j-1, k, ivy)
    temp0 = sk(i, j, k-1, 3)
    temp = w(i, j, k-1, ivy)
    tempd0 = fact*dvdzd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dvdzd
    wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + temp10*tempd0
    sid(i, j, k, 3) = sid(i, j, k, 3) + temp9*tempd0
    wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) - temp8*tempd0
    sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - temp7*tempd0
    wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + temp6*tempd0
    sjd(i, j, k, 3) = sjd(i, j, k, 3) + temp5*tempd0
    wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + temp4*tempd0
    skd(i, j, k, 3) = skd(i, j, k, 3) + temp3*tempd0
    wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) - temp2*tempd0
    sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - temp1*tempd0
    wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) - temp0*tempd0
    skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - temp*tempd0
    temp10 = si(i, j, k, 2)
    temp9 = w(i+1, j, k, ivy)
    temp8 = si(i-1, j, k, 2)
    temp7 = w(i-1, j, k, ivy)
    temp6 = sj(i, j, k, 2)
    temp5 = w(i, j+1, k, ivy)
    temp4 = sk(i, j, k, 2)
    temp3 = w(i, j, k+1, ivy)
    temp2 = sj(i, j-1, k, 2)
    temp1 = w(i, j-1, k, ivy)
    temp0 = sk(i, j, k-1, 2)
    temp = w(i, j, k-1, ivy)
    tempd0 = fact*dvdyd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dvdyd
    wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + temp10*tempd0
    sid(i, j, k, 2) = sid(i, j, k, 2) + temp9*tempd0
    wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) - temp8*tempd0
    sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - temp7*tempd0
    wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + temp6*tempd0
    sjd(i, j, k, 2) = sjd(i, j, k, 2) + temp5*tempd0
    wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + temp4*tempd0
    skd(i, j, k, 2) = skd(i, j, k, 2) + temp3*tempd0
    wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) - temp2*tempd0
    sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - temp1*tempd0
    wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) - temp0*tempd0
    skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - temp*tempd0
    temp10 = si(i, j, k, 1)
    temp9 = w(i+1, j, k, ivy)
    temp8 = si(i-1, j, k, 1)
    temp7 = w(i-1, j, k, ivy)
    temp6 = sj(i, j, k, 1)
    temp5 = w(i, j+1, k, ivy)
    temp4 = sk(i, j, k, 1)
    temp3 = w(i, j, k+1, ivy)
    temp2 = sj(i, j-1, k, 1)
    temp1 = w(i, j-1, k, ivy)
    temp0 = sk(i, j, k-1, 1)
    temp = w(i, j, k-1, ivy)
    tempd0 = fact*dvdxd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dvdxd
    wd(i+1, j, k, ivy) = wd(i+1, j, k, ivy) + temp10*tempd0
    sid(i, j, k, 1) = sid(i, j, k, 1) + temp9*tempd0
    wd(i-1, j, k, ivy) = wd(i-1, j, k, ivy) - temp8*tempd0
    sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - temp7*tempd0
    wd(i, j+1, k, ivy) = wd(i, j+1, k, ivy) + temp6*tempd0
    sjd(i, j, k, 1) = sjd(i, j, k, 1) + temp5*tempd0
    wd(i, j, k+1, ivy) = wd(i, j, k+1, ivy) + temp4*tempd0
    skd(i, j, k, 1) = skd(i, j, k, 1) + temp3*tempd0
    wd(i, j-1, k, ivy) = wd(i, j-1, k, ivy) - temp2*tempd0
    sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - temp1*tempd0
    wd(i, j, k-1, ivy) = wd(i, j, k-1, ivy) - temp0*tempd0
    skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - temp*tempd0
    temp10 = si(i, j, k, 3)
    temp9 = w(i+1, j, k, ivx)
    temp8 = si(i-1, j, k, 3)
    temp7 = w(i-1, j, k, ivx)
    temp6 = sj(i, j, k, 3)
    temp5 = w(i, j+1, k, ivx)
    temp4 = sk(i, j, k, 3)
    temp3 = w(i, j, k+1, ivx)
    temp2 = sj(i, j-1, k, 3)
    temp1 = w(i, j-1, k, ivx)
    temp0 = sk(i, j, k-1, 3)
    temp = w(i, j, k-1, ivx)
    tempd0 = fact*dudzd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dudzd
    wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + temp10*tempd0
    sid(i, j, k, 3) = sid(i, j, k, 3) + temp9*tempd0
    wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) - temp8*tempd0
    sid(i-1, j, k, 3) = sid(i-1, j, k, 3) - temp7*tempd0
    wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + temp6*tempd0
    sjd(i, j, k, 3) = sjd(i, j, k, 3) + temp5*tempd0
    wd(i, j, k+1, ivx) = wd(i, j, k+1, ivx) + temp4*tempd0
    skd(i, j, k, 3) = skd(i, j, k, 3) + temp3*tempd0
    wd(i, j-1, k, ivx) = wd(i, j-1, k, ivx) - temp2*tempd0
    sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) - temp1*tempd0
    wd(i, j, k-1, ivx) = wd(i, j, k-1, ivx) - temp0*tempd0
    skd(i, j, k-1, 3) = skd(i, j, k-1, 3) - temp*tempd0
    temp10 = si(i, j, k, 2)
    temp9 = w(i+1, j, k, ivx)
    temp8 = si(i-1, j, k, 2)
    temp7 = w(i-1, j, k, ivx)
    temp6 = sj(i, j, k, 2)
    temp5 = w(i, j+1, k, ivx)
    temp4 = sk(i, j, k, 2)
    temp3 = w(i, j, k+1, ivx)
    temp2 = sj(i, j-1, k, 2)
    temp1 = w(i, j-1, k, ivx)
    temp0 = sk(i, j, k-1, 2)
    temp = w(i, j, k-1, ivx)
    tempd0 = fact*dudyd
    factd = factd + (temp9*temp10-temp7*temp8+temp5*temp6+temp3*temp4-&
&     temp1*temp2-temp*temp0)*dudyd
    wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + temp10*tempd0
    sid(i, j, k, 2) = sid(i, j, k, 2) + temp9*tempd0
    wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) - temp8*tempd0
    sid(i-1, j, k, 2) = sid(i-1, j, k, 2) - temp7*tempd0
    wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + temp6*tempd0
    sjd(i, j, k, 2) = sjd(i, j, k, 2) + temp5*tempd0
    skd(i, j, k, 2) = skd(i, j, k, 2) + temp3*tempd0
    sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) - temp1*tempd0
    skd(i, j, k-1, 2) = skd(i, j, k-1, 2) - temp*tempd0
    temp1 = si(i, j, k, 1)
    temp = si(i-1, j, k, 1)
    temp3 = w(i-1, j, k, ivx)
    temp5 = w(i, j+1, k, ivx)
    temp6 = sk(i, j, k, 1)
    temp7 = w(i, j, k+1, ivx)
    temp8 = sj(i, j-1, k, 1)
    temp9 = w(i, j-1, k, ivx)
    temp10 = sk(i, j, k-1, 1)
    temp11 = w(i, j, k-1, ivx)
    tempd = fact*dudxd
    wd(i, j, k-1, ivx) = wd(i, j, k-1, ivx) - temp0*tempd0 - temp10*&
&     tempd
    wd(i, j-1, k, ivx) = wd(i, j-1, k, ivx) - temp2*tempd0 - temp8*tempd
    wd(i, j, k+1, ivx) = wd(i, j, k+1, ivx) + temp4*tempd0 + temp6*tempd
    temp0 = w(i+1, j, k, ivx)
    temp4 = sj(i, j, k, 1)
    factd = factd + (temp0*temp1-temp3*temp+temp5*temp4+temp7*temp6-&
&     temp9*temp8-temp11*temp10)*dudxd
    wd(i+1, j, k, ivx) = wd(i+1, j, k, ivx) + temp1*tempd
    sid(i, j, k, 1) = sid(i, j, k, 1) + temp0*tempd
    wd(i-1, j, k, ivx) = wd(i-1, j, k, ivx) - temp*tempd
    sid(i-1, j, k, 1) = sid(i-1, j, k, 1) - temp3*tempd
    wd(i, j+1, k, ivx) = wd(i, j+1, k, ivx) + temp4*tempd
    sjd(i, j, k, 1) = sjd(i, j, k, 1) + temp5*tempd
    skd(i, j, k, 1) = skd(i, j, k, 1) + temp7*tempd
    sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) - temp9*tempd
    skd(i, j, k-1, 1) = skd(i, j, k-1, 1) - temp11*tempd
    temp2 = 2.0*vol(i, j, k)
    vold(i, j, k) = vold(i, j, k) - 2.0*factd/temp2**2
    temp = w(i, j, k, ivz)
    temp0 = w(i, j, k, ivy)
    temp1 = w(i, j, k, ivx)
    if (temp1**2 + temp0**2 + temp**2 .eq. 0.0_8) then
      tempd = 0.0_8
    else
      tempd = ud/(2.0*sqrt(temp1**2+temp0**2+temp**2))
    end if
    wd(i, j, k, ivx) = wd(i, j, k, ivx) + 2*temp1*tempd
    wd(i, j, k, ivy) = wd(i, j, k, ivy) + 2*temp0*tempd
    wd(i, j, k, ivz) = wd(i, j, k, ivz) + 2*temp*tempd
    re_thetat_eqd = 0.0_8
  end subroutine solve_local_re_thetat_eq_b

  subroutine solve_local_re_thetat_eq(re_thetat_eq, i, j, k)
    use blockpointers
    use constants
    use paramturb
    implicit none
! input/output variables
    integer(kind=inttype), intent(in) :: i, j, k
    real(kind=realtype), intent(out) :: re_thetat_eq
! local variables
    real(kind=realtype) :: u, u_inv, fact, du_dx, du_dy, du_dz, du_ds, &
&   tu, f1, f2, f3, f
    real(kind=realtype) :: dudx, dudy, dudz, dvdx, dvdy, dvdz, dwdx, &
&   dwdy, dwdz
    real(kind=realtype) :: lambda, thetat, residum, thetat_old, &
&   residum_old, thetat_new
    real(kind=realtype) :: re_thetat_eq_1, re_thetat_eq_2
    integer(kind=inttype) :: n
    intrinsic sqrt
    intrinsic max
    intrinsic min
    intrinsic exp
    intrinsic abs
    real(kind=realtype) :: x1
    real(kind=realtype) :: x2
    real(kind=realtype) :: abs0
    real(kind=realtype) :: abs1
    u = sqrt(w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 + w(i, j, k, ivz)**&
&     2)
    u_inv = 1.0/u
! compute the gradient of u in the cell center. use is made
! of the fact that the surrounding normals sum up to zero,
! such that the cell i,j,k does not give a contribution.
! since the gradient is scaled by a factor of 2*vol, we need to account for that
    fact = 1.0/(vol(i, j, k)*2.0)
    dudx = (w(i+1, j, k, ivx)*si(i, j, k, 1)-w(i-1, j, k, ivx)*si(i-1, j&
&     , k, 1)+w(i, j+1, k, ivx)*sj(i, j, k, 1)-w(i, j-1, k, ivx)*sj(i, j&
&     -1, k, 1)+w(i, j, k+1, ivx)*sk(i, j, k, 1)-w(i, j, k-1, ivx)*sk(i&
&     , j, k-1, 1))*fact
    dudy = (w(i+1, j, k, ivx)*si(i, j, k, 2)-w(i-1, j, k, ivx)*si(i-1, j&
&     , k, 2)+w(i, j+1, k, ivx)*sj(i, j, k, 2)-w(i, j-1, k, ivx)*sj(i, j&
&     -1, k, 2)+w(i, j, k+1, ivx)*sk(i, j, k, 2)-w(i, j, k-1, ivx)*sk(i&
&     , j, k-1, 2))*fact
    dudz = (w(i+1, j, k, ivx)*si(i, j, k, 3)-w(i-1, j, k, ivx)*si(i-1, j&
&     , k, 3)+w(i, j+1, k, ivx)*sj(i, j, k, 3)-w(i, j-1, k, ivx)*sj(i, j&
&     -1, k, 3)+w(i, j, k+1, ivx)*sk(i, j, k, 3)-w(i, j, k-1, ivx)*sk(i&
&     , j, k-1, 3))*fact
! idem for the gradient of v.
    dvdx = (w(i+1, j, k, ivy)*si(i, j, k, 1)-w(i-1, j, k, ivy)*si(i-1, j&
&     , k, 1)+w(i, j+1, k, ivy)*sj(i, j, k, 1)-w(i, j-1, k, ivy)*sj(i, j&
&     -1, k, 1)+w(i, j, k+1, ivy)*sk(i, j, k, 1)-w(i, j, k-1, ivy)*sk(i&
&     , j, k-1, 1))*fact
    dvdy = (w(i+1, j, k, ivy)*si(i, j, k, 2)-w(i-1, j, k, ivy)*si(i-1, j&
&     , k, 2)+w(i, j+1, k, ivy)*sj(i, j, k, 2)-w(i, j-1, k, ivy)*sj(i, j&
&     -1, k, 2)+w(i, j, k+1, ivy)*sk(i, j, k, 2)-w(i, j, k-1, ivy)*sk(i&
&     , j, k-1, 2))*fact
    dvdz = (w(i+1, j, k, ivy)*si(i, j, k, 3)-w(i-1, j, k, ivy)*si(i-1, j&
&     , k, 3)+w(i, j+1, k, ivy)*sj(i, j, k, 3)-w(i, j-1, k, ivy)*sj(i, j&
&     -1, k, 3)+w(i, j, k+1, ivy)*sk(i, j, k, 3)-w(i, j, k-1, ivy)*sk(i&
&     , j, k-1, 3))*fact
! and for the gradient of w.
    dwdx = (w(i+1, j, k, ivz)*si(i, j, k, 1)-w(i-1, j, k, ivz)*si(i-1, j&
&     , k, 1)+w(i, j+1, k, ivz)*sj(i, j, k, 1)-w(i, j-1, k, ivz)*sj(i, j&
&     -1, k, 1)+w(i, j, k+1, ivz)*sk(i, j, k, 1)-w(i, j, k-1, ivz)*sk(i&
&     , j, k-1, 1))*fact
    dwdy = (w(i+1, j, k, ivz)*si(i, j, k, 2)-w(i-1, j, k, ivz)*si(i-1, j&
&     , k, 2)+w(i, j+1, k, ivz)*sj(i, j, k, 2)-w(i, j-1, k, ivz)*sj(i, j&
&     -1, k, 2)+w(i, j, k+1, ivz)*sk(i, j, k, 2)-w(i, j, k-1, ivz)*sk(i&
&     , j, k-1, 2))*fact
    dwdz = (w(i+1, j, k, ivz)*si(i, j, k, 3)-w(i-1, j, k, ivz)*si(i-1, j&
&     , k, 3)+w(i, j+1, k, ivz)*sj(i, j, k, 3)-w(i, j-1, k, ivz)*sj(i, j&
&     -1, k, 3)+w(i, j, k+1, ivz)*sk(i, j, k, 3)-w(i, j, k-1, ivz)*sk(i&
&     , j, k-1, 3))*fact
    du_dx = u_inv*(w(i, j, k, ivx)*dudx+w(i, j, k, ivy)*dudy+w(i, j, k, &
&     ivz)*dudz)
    du_dy = u_inv*(w(i, j, k, ivx)*dvdx+w(i, j, k, ivy)*dvdy+w(i, j, k, &
&     ivz)*dvdz)
    du_dz = u_inv*(w(i, j, k, ivx)*dwdx+w(i, j, k, ivy)*dwdy+w(i, j, k, &
&     ivz)*dwdz)
    du_ds = w(i, j, k, ivx)/u*du_dx + w(i, j, k, ivy)/u*du_dy + w(i, j, &
&     k, ivz)/u*du_dz
    tu = 100.0*sqrt(2*w(i, j, k, itu1)/3)/u
    if (tu .lt. 0.027) then
      tu = 0.027
    else
      tu = tu
    end if
! now we need to solve for theta through newton's method. the number of iterations is hard-coded so tapenade is 
! able to differentiate it
    thetat = 0.01
    do n=1,10
      lambda = w(i, j, k, irho)*thetat**2/rlv(i, j, k)*du_ds
      if (lambda .gt. 0.1) then
        x1 = 0.1
      else
        x1 = lambda
      end if
      if (x1 .lt. -0.1) then
        lambda = -0.1
      else
        lambda = x1
      end if
! compute f function
      if (lambda .le. 1.0e-9) then
        f = 1.0 + (12.986*lambda+123.66*lambda**2+405.689*lambda**3)*exp&
&         (-((tu/1.5)**1.5))
      else
        f = 1.0 + 0.275*(1.0-exp(-(35.0*lambda)))*exp(-(tu/0.5))
      end if
      if (tu .gt. 1.3) then
        re_thetat_eq_1 = 331.50*(tu-0.5658)**(-0.671)*f
      else
        re_thetat_eq_1 = (1173.51-589.428*tu+0.2196*tu**(-2))*f
      end if
      re_thetat_eq_2 = w(i, j, k, irho)*u*thetat/rlv(i, j, k)
! residum which should go to 0
      residum = re_thetat_eq_1 - re_thetat_eq_2
      if (residum .ge. 0.) then
        abs0 = residum
      else
        abs0 = -residum
      end if
! exit if converged
      if (abs0 .lt. 1e-9) then
        goto 100
      else
! apply the secant method update
        if (n .gt. 1) then
          if (residum - residum_old .ge. 0.) then
            abs1 = residum - residum_old
          else
            abs1 = -(residum-residum_old)
          end if
          if (abs1 .gt. 1.0e-12) then
            thetat_new = thetat - residum*(thetat_old-thetat)/(&
&             residum_old-residum)
          else
            print*, &
&           'warning: small denominator in secant method, stopping.'
            goto 100
          end if
        else
! initial step
          thetat_new = 0.5*thetat
        end if
! update values for next iteration
        thetat_old = thetat
        residum_old = residum
        thetat = thetat_new
      end if
    end do
 100 if (re_thetat_eq_1 .lt. 20.0) then
      x2 = 20.0
    else
      x2 = re_thetat_eq_1
    end if
    if (x2 .gt. 1.0e10) then
      re_thetat_eq = 1.0e10
    else
      re_thetat_eq = x2
    end if
  end subroutine solve_local_re_thetat_eq

!  differentiation of gammarethetasource in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *w *rlv *scratch *vol *d2wall
!                *si *sj *sk
!   with respect to varying inputs: *w *rlv *scratch *vol *d2wall
!                *si *sj *sk
!   rw status of diff variables: *w:incr *rlv:incr *scratch:in-out
!                *vol:incr *d2wall:incr *si:incr *sj:incr *sk:incr
!   plus diff mem management of: w:in rlv:in scratch:in vol:in
!                d2wall:in si:in sj:in sk:in
  subroutine gammarethetasource_b()
    use blockpointers
    use constants
    use variableconstants
    use paramturb
    implicit none
    integer(kind=inttype) :: i, j, k
    real(kind=realtype) :: re_thetat_eq, u2, u, lambda_theta, delta, &
&   f_theta_t, t, r_t, re_theta_c
    real(kind=realtype) :: re_thetat_eqd, u2d, deltad, f_theta_td, td, &
&   r_td, re_theta_cd
    real(kind=realtype) :: re_s, f_length1, f_length, f_onset1, f_onset&
&   , f_turb, p_gamma, e_gamma, p_thetat
    real(kind=realtype) :: re_sd, f_length1d, f_lengthd, f_onset1d, &
&   f_onsetd, f_turbd, p_gammad, e_gammad, p_thetatd
    real(kind=realtype) :: re_omega, f_wake, f_sublayer, f_onset2, &
&   f_onset3
    real(kind=realtype) :: re_omegad, f_waked, f_sublayerd, f_onset2d, &
&   f_onset3d
    real(kind=realtype) :: rhoi, vort
    real(kind=realtype) :: rhoid, vortd
    intrinsic mod
    intrinsic sqrt
    intrinsic exp
    intrinsic max
    intrinsic min
    real(kind=realtype) :: x1
    real(kind=realtype) :: x1d
    real(kind=realtype) :: x2
    real(kind=realtype) :: x2d
    real(kind=realtype) :: x3
    real(kind=realtype) :: x3d
    real(kind=realtype) :: temp
    real(kind=realtype) :: temp0
    real(kind=realtype) :: temp1
    real(kind=realtype) :: tempd
    real(kind=realtype) :: tempd0
    real(kind=realtype) :: temp2
    real(kind=realtype) :: tempd1
    real(kind=realtype) :: temp3
    real(kind=realtype) :: tempd2
    real(kind=realtype) :: tempd3
    real(kind=realtype) :: temp4
    real(kind=realtype) :: temp5
    real(kind=realtype) :: temp6
    real(kind=realtype) :: temp7
    real(kind=realtype) :: tempd4
    real(kind=realtype) :: temp8
    real(kind=realtype) :: tempd5
    real(kind=realtype) :: tempd6
    real(kind=realtype) :: tempd7
    real(kind=realtype) :: tempd8
    integer :: branch
    integer :: ii
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      rhoi = one/w(i, j, k, irho)
      vort = sqrt(scratch(i, j, k, ivorticity))
! compute re_thetat_eq
      call solve_local_re_thetat_eq(re_thetat_eq, i, j, k)
      u2 = w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 + w(i, j, k, ivz)**2
      re_omega = w(i, j, k, irho)*w(i, j, k, itu2)*d2wall(i, j, k)**2/&
&       rlv(i, j, k)
      f_wake = exp(-((re_omega/1e5)**2))
      f_sublayer = exp(-((re_omega/200)**2))
      delta = 375.0*vort*rlv(i, j, k)*w(i, j, k, itransition2)*d2wall(i&
&       , j, k)/(w(i, j, k, irho)*u2)
      x3 = f_wake*exp(-((d2wall(i, j, k)/delta)**4))
      if (x3 .lt. 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2-1&
&         ))**2) then
        x1 = 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2-1))**2
        call pushcontrol1b(0)
      else
        x1 = x3
        call pushcontrol1b(1)
      end if
      if (x1 .gt. 1.0) then
        f_theta_t = 1.0
        call pushcontrol1b(0)
      else
        f_theta_t = x1
        call pushcontrol1b(1)
      end if
      t = 500.0*rlv(i, j, k)/(w(i, j, k, irho)*u2)
! todo: save this in scratch
      r_t = w(i, j, k, irho)*w(i, j, k, itu1)/(rlv(i, j, k)*w(i, j, k, &
&       itu2))
      if (w(i, j, k, itransition2) .le. 1870.0) then
        re_theta_c = -3.96035 + 1.0120656*w(i, j, k, itransition2) + (-&
&         0.868230e-3)*w(i, j, k, itransition2)**2 + 0.696506e-6*w(i, j&
&         , k, itransition2)**3 + (-0.174105e-9)*w(i, j, k, itransition2&
&         )**4
        call pushcontrol1b(0)
      else
        re_theta_c = w(i, j, k, itransition2) - (593.11+0.482*(w(i, j, k&
&         , itransition2)-1870.0))
        call pushcontrol1b(1)
      end if
!! todo: save this in scratch
      re_s = w(i, j, k, irho)*sqrt(scratch(i, j, k, istrain))*d2wall(i, &
&       j, k)**2/rlv(i, j, k)
! compute f_length1 based on the given conditions
      if (w(i, j, k, itransition2) .lt. 400.0) then
        f_length1 = 39.8189 - 0.0119270*w(i, j, k, itransition2) - &
&         0.000132567*w(i, j, k, itransition2)**2
        call pushcontrol2b(3)
      else if (w(i, j, k, itransition2) .ge. 400.0 .and. w(i, j, k, &
&         itransition2) .lt. 596.0) then
        f_length1 = 263.404 - 1.23939*w(i, j, k, itransition2) + &
&         0.00194548*w(i, j, k, itransition2)**2 - 1.01695e-6*w(i, j, k&
&         , itransition2)**3
        call pushcontrol2b(2)
      else if (w(i, j, k, itransition2) .ge. 596.0 .and. w(i, j, k, &
&         itransition2) .lt. 1200.0) then
        f_length1 = 0.5 - (w(i, j, k, itransition2)-596.0)*3.0e-4
        call pushcontrol2b(1)
      else
        call pushcontrol2b(0)
        f_length1 = 0.3188
      end if
      f_length = f_length1*(1-f_sublayer) + 40*f_sublayer
      f_onset1 = re_s/(2.193*re_theta_c)
      if (f_onset1 .lt. f_onset1**4) then
        x2 = f_onset1**4
        call pushcontrol1b(0)
      else
        x2 = f_onset1
        call pushcontrol1b(1)
      end if
      if (x2 .gt. 2.0) then
        f_onset2 = 2.0
        call pushcontrol1b(0)
      else
        f_onset2 = x2
        call pushcontrol1b(1)
      end if
      if (1.0 - (r_t/2.5)**3 .lt. zero) then
        call pushcontrol1b(0)
        f_onset3 = zero
      else
        f_onset3 = 1.0 - (r_t/2.5)**3
        call pushcontrol1b(1)
      end if
      if (f_onset2 - f_onset3 .lt. zero) then
        f_onset = zero
        call pushcontrol1b(0)
      else
        f_onset = f_onset2 - f_onset3
        call pushcontrol1b(1)
      end if
      f_turb = exp(-(r_t/4))**4
! since we need to divide by rho, rho does not appear here anymore
      p_gamma = f_length*rlmca1*w(i, j, k, irho)*sqrt(scratch(i, j, k, &
&       istrain))*sqrt(w(i, j, k, itransition1)*f_onset)*(1.0-rlmce1*w(i&
&       , j, k, itransition1))
      e_gamma = rlmca2*w(i, j, k, irho)*vort*w(i, j, k, itransition1)*&
&       f_turb*(rlmce2*w(i, j, k, itransition1)-1.0)
      p_thetat = rlmcthetat*w(i, j, k, irho)/t*(re_thetat_eq-w(i, j, k, &
&       itransition2))*(1.0-f_theta_t)
! print *, 'source terms: gamma, thetat', scratch(i, j, k, istransition1), scratch(i, j, k, istransition2)
      p_thetatd = rhoi*scratchd(i, j, k, istransition2)
      rhoid = p_thetat*scratchd(i, j, k, istransition2)
      scratchd(i, j, k, istransition2) = 0.0_8
      p_gammad = rhoi*scratchd(i, j, k, istransition1)
      e_gammad = -(rhoi*scratchd(i, j, k, istransition1))
      rhoid = rhoid + (p_gamma-e_gamma)*scratchd(i, j, k, istransition1)
      scratchd(i, j, k, istransition1) = 0.0_8
      temp7 = (-f_theta_t+1.0)/t
      temp6 = w(i, j, k, irho)
      tempd5 = (re_thetat_eq-w(i, j, k, itransition2))*rlmcthetat*&
&       p_thetatd
      tempd8 = temp6*temp7*rlmcthetat*p_thetatd
      re_thetat_eqd = tempd8
      wd(i, j, k, itransition2) = wd(i, j, k, itransition2) - tempd8
      wd(i, j, k, irho) = wd(i, j, k, irho) + temp7*tempd5
      tempd4 = temp6*tempd5/t
      f_theta_td = -tempd4
      td = -(temp7*tempd4)
      temp8 = rlmce2*w(i, j, k, itransition1) - 1.0
      temp7 = w(i, j, k, itransition1)
      temp5 = w(i, j, k, irho)
      tempd6 = temp7*temp8*rlmca2*e_gammad
      tempd7 = temp5*vort*f_turb*rlmca2*e_gammad
      wd(i, j, k, itransition1) = wd(i, j, k, itransition1) + (temp8+&
&       rlmce2*temp7)*tempd7
      wd(i, j, k, irho) = wd(i, j, k, irho) + vort*f_turb*tempd6
      vortd = f_turb*temp5*tempd6
      f_turbd = vort*temp5*tempd6
      temp3 = -(rlmce1*w(i, j, k, itransition1)) + 1.0
      temp2 = w(i, j, k, irho)
      temp0 = w(i, j, k, itransition1)
      temp = temp0*f_onset
      temp4 = sqrt(temp)
      temp5 = scratch(i, j, k, istrain)
      temp6 = sqrt(temp5)
      tempd = f_length*temp2*temp3*rlmca1*p_gammad
      tempd4 = temp6*temp4*rlmca1*p_gammad
      tempd5 = temp3*tempd4
      wd(i, j, k, itransition1) = wd(i, j, k, itransition1) - rlmce1*&
&       f_length*temp2*tempd4
      f_lengthd = temp2*tempd5
      wd(i, j, k, irho) = wd(i, j, k, irho) + f_length*tempd5
      if (.not.temp5 .eq. 0.0_8) scratchd(i, j, k, istrain) = scratchd(i&
&         , j, k, istrain) + temp4*tempd/(2.0*temp6)
      if (temp .eq. 0.0_8) then
        tempd0 = 0.0_8
      else
        tempd0 = temp6*tempd/(2.0*temp4)
      end if
      wd(i, j, k, itransition1) = wd(i, j, k, itransition1) + f_onset*&
&       tempd0
      f_onsetd = temp0*tempd0
      r_td = -(exp(-(r_t/4))**4*f_turbd)
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        f_onset2d = 0.0_8
        f_onset3d = 0.0_8
      else
        f_onset2d = f_onsetd
        f_onset3d = -f_onsetd
      end if
      call popcontrol1b(branch)
      if (branch .ne. 0) r_td = r_td - 3*r_t**2*f_onset3d/2.5**3
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        x2d = 0.0_8
      else
        x2d = f_onset2d
      end if
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        f_onset1d = 4*f_onset1**3*x2d
      else
        f_onset1d = x2d
      end if
      tempd2 = f_onset1d/(2.193*re_theta_c)
      re_sd = tempd2
      re_theta_cd = -(re_s*tempd2/re_theta_c)
      f_length1d = (1-f_sublayer)*f_lengthd
      f_sublayerd = (40-f_length1)*f_lengthd
      call popcontrol2b(branch)
      if (branch .lt. 2) then
        if (branch .ne. 0) wd(i, j, k, itransition2) = wd(i, j, k, &
&           itransition2) - 3.0e-4*f_length1d
      else if (branch .eq. 2) then
        wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + (2*w(i, &
&         j, k, itransition2)*0.00194548-3*w(i, j, k, itransition2)**2*&
&         1.01695e-6-1.23939)*f_length1d
      else
        wd(i, j, k, itransition2) = wd(i, j, k, itransition2) - (2*w(i, &
&         j, k, itransition2)*0.000132567+0.0119270)*f_length1d
      end if
      temp3 = scratch(i, j, k, istrain)
      temp2 = sqrt(temp3)
      temp1 = d2wall(i, j, k)
      temp0 = w(i, j, k, irho)/rlv(i, j, k)
      tempd1 = temp1**2*temp2*re_sd/rlv(i, j, k)
      d2walld(i, j, k) = d2walld(i, j, k) + 2*temp1*temp0*temp2*re_sd
      if (.not.temp3 .eq. 0.0_8) scratchd(i, j, k, istrain) = scratchd(i&
&         , j, k, istrain) + temp0*temp1**2*re_sd/(2.0*temp2)
      wd(i, j, k, irho) = wd(i, j, k, irho) + tempd1
      rlvd(i, j, k) = rlvd(i, j, k) - temp0*tempd1
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + (3*w(i, &
&         j, k, itransition2)**2*0.696506e-6-4*w(i, j, k, itransition2)&
&         **3*0.174105e-9-2*w(i, j, k, itransition2)*0.868230e-3+&
&         1.0120656)*re_theta_cd
      else
        wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + 0.518*&
&         re_theta_cd
      end if
      temp3 = w(i, j, k, itu2)
      temp2 = rlv(i, j, k)*temp3
      temp0 = w(i, j, k, itu1)
      temp = w(i, j, k, irho)
      tempd = r_td/temp2
      wd(i, j, k, irho) = wd(i, j, k, irho) + temp0*tempd
      wd(i, j, k, itu1) = wd(i, j, k, itu1) + temp*tempd
      tempd3 = -(temp*temp0*tempd/temp2)
      rlvd(i, j, k) = rlvd(i, j, k) + temp3*tempd3
      wd(i, j, k, itu2) = wd(i, j, k, itu2) + rlv(i, j, k)*tempd3
      temp3 = w(i, j, k, irho)
      temp2 = temp3*u2
      tempd = 500.0*td/temp2
      rlvd(i, j, k) = rlvd(i, j, k) + tempd
      tempd3 = -(rlv(i, j, k)*tempd/temp2)
      wd(i, j, k, irho) = wd(i, j, k, irho) + u2*tempd3
      u2d = temp3*tempd3
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        x1d = 0.0_8
      else
        x1d = f_theta_td
      end if
      call popcontrol1b(branch)
      if (branch .eq. 0) then
        wd(i, j, k, itransition1) = wd(i, j, k, itransition1) - rlmce2*2&
&         *(rlmce2*w(i, j, k, itransition1)-1.0)*x1d/(rlmce2-1)**2
        x3d = 0.0_8
      else
        x3d = x1d
      end if
      temp3 = d2wall(i, j, k)/delta
      temp2 = -(temp3**4)
      f_waked = exp(temp2)*x3d
      tempd2 = -(4*temp3**3*exp(temp2)*f_wake*x3d/delta)
      d2walld(i, j, k) = d2walld(i, j, k) + tempd2
      deltad = -(temp3*tempd2)
      temp1 = w(i, j, k, irho)
      temp0 = vort*rlv(i, j, k)/(temp1*u2)
      temp2 = w(i, j, k, itransition2)
      tempd0 = temp0*375.0*deltad
      tempd1 = temp2*d2wall(i, j, k)*375.0*deltad/(temp1*u2)
      vortd = vortd + rlv(i, j, k)*tempd1
      tempd2 = -(temp0*tempd1)
      wd(i, j, k, irho) = wd(i, j, k, irho) + u2*tempd2
      u2d = u2d + temp1*tempd2
      wd(i, j, k, itransition2) = wd(i, j, k, itransition2) + d2wall(i, &
&       j, k)*tempd0
      re_omegad = -(2*re_omega*exp(-((re_omega/200)**2))*f_sublayerd/200&
&       **2) - 2*re_omega*exp(-((re_omega/1e5)**2))*f_waked/1e5**2
      temp = d2wall(i, j, k)
      temp0 = w(i, j, k, itu2)
      temp1 = w(i, j, k, irho)/rlv(i, j, k)
      d2walld(i, j, k) = d2walld(i, j, k) + temp2*tempd0 + 2*temp*temp0*&
&       temp1*re_omegad
      tempd = temp0*temp**2*re_omegad/rlv(i, j, k)
      rlvd(i, j, k) = rlvd(i, j, k) + vort*tempd1 - temp1*tempd
      wd(i, j, k, itu2) = wd(i, j, k, itu2) + temp**2*temp1*re_omegad
      wd(i, j, k, irho) = wd(i, j, k, irho) + tempd
      wd(i, j, k, ivx) = wd(i, j, k, ivx) + 2*w(i, j, k, ivx)*u2d
      wd(i, j, k, ivy) = wd(i, j, k, ivy) + 2*w(i, j, k, ivy)*u2d
      wd(i, j, k, ivz) = wd(i, j, k, ivz) + 2*w(i, j, k, ivz)*u2d
      call solve_local_re_thetat_eq_b(re_thetat_eq, re_thetat_eqd, i, j&
&                               , k)
      if (.not.scratch(i, j, k, ivorticity) .eq. 0.0_8) scratchd(i, j, k&
&       , ivorticity) = scratchd(i, j, k, ivorticity) + vortd/(2.0*sqrt(&
&         scratch(i, j, k, ivorticity)))
      temp = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp**2
    end do
  end subroutine gammarethetasource_b

  subroutine gammarethetasource()
    use blockpointers
    use constants
    use variableconstants
    use paramturb
    implicit none
    integer(kind=inttype) :: i, j, k
    real(kind=realtype) :: re_thetat_eq, u2, u, lambda_theta, delta, &
&   f_theta_t, t, r_t, re_theta_c
    real(kind=realtype) :: re_s, f_length1, f_length, f_onset1, f_onset&
&   , f_turb, p_gamma, e_gamma, p_thetat
    real(kind=realtype) :: re_omega, f_wake, f_sublayer, f_onset2, &
&   f_onset3
    real(kind=realtype) :: rhoi, vort
    intrinsic mod
    intrinsic sqrt
    intrinsic exp
    intrinsic max
    intrinsic min
    real(kind=realtype) :: x1
    real(kind=realtype) :: x2
    real(kind=realtype) :: x3
    integer :: ii
!$ad ii-loop
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      rhoi = one/w(i, j, k, irho)
      vort = sqrt(scratch(i, j, k, ivorticity))
! compute re_thetat_eq
      call solve_local_re_thetat_eq(re_thetat_eq, i, j, k)
      u2 = w(i, j, k, ivx)**2 + w(i, j, k, ivy)**2 + w(i, j, k, ivz)**2
      u = sqrt(u2)
      re_omega = w(i, j, k, irho)*w(i, j, k, itu2)*d2wall(i, j, k)**2/&
&       rlv(i, j, k)
      f_wake = exp(-((re_omega/1e5)**2))
      f_sublayer = exp(-((re_omega/200)**2))
      delta = 375.0*vort*rlv(i, j, k)*w(i, j, k, itransition2)*d2wall(i&
&       , j, k)/(w(i, j, k, irho)*u2)
      x3 = f_wake*exp(-((d2wall(i, j, k)/delta)**4))
      if (x3 .lt. 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2-1&
&         ))**2) then
        x1 = 1.0 - ((rlmce2*w(i, j, k, itransition1)-1.0)/(rlmce2-1))**2
      else
        x1 = x3
      end if
      if (x1 .gt. 1.0) then
        f_theta_t = 1.0
      else
        f_theta_t = x1
      end if
      t = 500.0*rlv(i, j, k)/(w(i, j, k, irho)*u2)
! todo: save this in scratch
      r_t = w(i, j, k, irho)*w(i, j, k, itu1)/(rlv(i, j, k)*w(i, j, k, &
&       itu2))
      if (w(i, j, k, itransition2) .le. 1870.0) then
        re_theta_c = -3.96035 + 1.0120656*w(i, j, k, itransition2) + (-&
&         0.868230e-3)*w(i, j, k, itransition2)**2 + 0.696506e-6*w(i, j&
&         , k, itransition2)**3 + (-0.174105e-9)*w(i, j, k, itransition2&
&         )**4
      else
        re_theta_c = w(i, j, k, itransition2) - (593.11+0.482*(w(i, j, k&
&         , itransition2)-1870.0))
      end if
!! todo: save this in scratch
      re_s = w(i, j, k, irho)*sqrt(scratch(i, j, k, istrain))*d2wall(i, &
&       j, k)**2/rlv(i, j, k)
! compute f_length1 based on the given conditions
      if (w(i, j, k, itransition2) .lt. 400.0) then
        f_length1 = 39.8189 - 0.0119270*w(i, j, k, itransition2) - &
&         0.000132567*w(i, j, k, itransition2)**2
      else if (w(i, j, k, itransition2) .ge. 400.0 .and. w(i, j, k, &
&         itransition2) .lt. 596.0) then
        f_length1 = 263.404 - 1.23939*w(i, j, k, itransition2) + &
&         0.00194548*w(i, j, k, itransition2)**2 - 1.01695e-6*w(i, j, k&
&         , itransition2)**3
      else if (w(i, j, k, itransition2) .ge. 596.0 .and. w(i, j, k, &
&         itransition2) .lt. 1200.0) then
        f_length1 = 0.5 - (w(i, j, k, itransition2)-596.0)*3.0e-4
      else
        f_length1 = 0.3188
      end if
      f_length = f_length1*(1-f_sublayer) + 40*f_sublayer
      f_onset1 = re_s/(2.193*re_theta_c)
      if (f_onset1 .lt. f_onset1**4) then
        x2 = f_onset1**4
      else
        x2 = f_onset1
      end if
      if (x2 .gt. 2.0) then
        f_onset2 = 2.0
      else
        f_onset2 = x2
      end if
      if (1.0 - (r_t/2.5)**3 .lt. zero) then
        f_onset3 = zero
      else
        f_onset3 = 1.0 - (r_t/2.5)**3
      end if
      if (f_onset2 - f_onset3 .lt. zero) then
        f_onset = zero
      else
        f_onset = f_onset2 - f_onset3
      end if
      f_turb = exp(-(r_t/4))**4
! since we need to divide by rho, rho does not appear here anymore
      p_gamma = f_length*rlmca1*w(i, j, k, irho)*sqrt(scratch(i, j, k, &
&       istrain))*sqrt(w(i, j, k, itransition1)*f_onset)*(1.0-rlmce1*w(i&
&       , j, k, itransition1))
      e_gamma = rlmca2*w(i, j, k, irho)*vort*w(i, j, k, itransition1)*&
&       f_turb*(rlmce2*w(i, j, k, itransition1)-1.0)
      p_thetat = rlmcthetat*w(i, j, k, irho)/t*(re_thetat_eq-w(i, j, k, &
&       itransition2))*(1.0-f_theta_t)
      scratch(i, j, k, istransition1) = (p_gamma-e_gamma)*rhoi
      scratch(i, j, k, istransition2) = p_thetat*rhoi
! print *, 'source terms: gamma, thetat', scratch(i, j, k, istransition1), scratch(i, j, k, istransition2)
    end do
  end subroutine gammarethetasource

!  differentiation of gammarethetaviscous in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *rev *w *rlv *scratch *vol
!                *si *sj *sk
!   with respect to varying inputs: *rev *w *rlv *scratch *vol
!                *si *sj *sk
!   rw status of diff variables: *rev:incr *w:incr *rlv:incr *scratch:in-out
!                *vol:incr *si:incr *sj:incr *sk:incr
!   plus diff mem management of: rev:in w:in rlv:in scratch:in
!                vol:in si:in sj:in sk:in
  subroutine gammarethetaviscous_b()
    use blockpointers
    use constants
    use variableconstants
    use paramturb
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rhoi
    real(kind=realtype) :: rhoid
    real(kind=realtype) :: voli, volmi, volpi
    real(kind=realtype) :: volid, volmid, volpid
    real(kind=realtype) :: xm, ym, zm, xp, yp, zp, xa, ya, za
    real(kind=realtype) :: xmd, ymd, zmd, xpd, ypd, zpd, xad, yad, zad
    real(kind=realtype) :: mulm, mulp, muem, muep
    real(kind=realtype) :: mulmd, mulpd, muemd, muepd
    real(kind=realtype) :: ttm, ttp
    real(kind=realtype) :: ttmd, ttpd
    real(kind=realtype) :: c1m, c1p, c10, c2m, c2p, c20
    real(kind=realtype) :: c1md, c1pd, c10d, c2md, c2pd, c20d
    real(kind=realtype) :: rblank
    intrinsic mod
    real(kind=realtype) :: temp
    real(kind=realtype) :: tempd
    real(kind=realtype) :: temp0
    real(kind=realtype) :: tempd0
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in xi-direction, i.e. along the
! line i = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in xi-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in xi-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dxi^2 = d/dxi (d/dxi i+1/2 - d/dxi i-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dxi derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the gamma-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i-1, j, k)+rlv(i, j, k))
      mulp = half*(rlv(i+1, j, k)+rlv(i, j, k))
      muem = half*(rev(i-1, j, k)+rev(i, j, k))
      muep = half*(rev(i+1, j, k)+rev(i, j, k))
      c1m = ttm*(mulm+muem/rlmsigmaf)*rhoi
      c1p = ttp*(mulp+muep/rlmsigmaf)*rhoi
      c10 = c1m + c1p
! and the re_theta_t term.
      muem = half*(rev(i-1, j, k)+rev(i, j, k))
      muep = half*(rev(i+1, j, k)+rev(i, j, k))
      c2m = ttm*rlmsigmathetat*(mulm+muem)*rhoi
      c2p = ttp*rlmsigmathetat*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
! #ifndef 1
!                         b1 = -c1m
!                         c1 = c10
!                         d1 = -c1p
!                         b2 = -c2m
!                         c2 = c20
!                         d2 = -c2p
!                         ! update the central jacobian. for nonboundary cells this
!                         ! is simply c1 and c2. for boundary cells this is slightly
!                         ! more complicated, because the boundary conditions are
!                         ! treated implicitly and the off-diagonal terms b1, b2 and
!                         ! d1, d2 must be taken into account.
!                         ! the boundary conditions are only treated implicitly if
!                         ! the diagonal dominance of the matrix is increased.
!                         if (i == 2) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - b1 * max(bmti1(j, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - b1 * bmti1(j, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - b2 * bmti1(j, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - b2 * max(bmti1(j, k, itu2, itu2), zero)
!                         else if (i == il) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - d1 * max(bmti2(j, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - d1 * bmti2(j, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - d2 * bmti2(j, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - d2 * max(bmti2(j, k, itu2, itu2), zero)
!                         else
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
!                         end if
! #endif
      c10d = -(w(i, j, k, itransition1)*scratchd(i, j, k, istransition1)&
&       )
      c20d = -(w(i, j, k, itransition2)*scratchd(i, j, k, istransition2)&
&       )
      c2md = w(i-1, j, k, itransition2)*scratchd(i, j, k, istransition2)&
&       + c20d
      wd(i-1, j, k, itransition2) = wd(i-1, j, k, itransition2) + c2m*&
&       scratchd(i, j, k, istransition2)
      c2pd = w(i+1, j, k, itransition2)*scratchd(i, j, k, istransition2)&
&       + c20d
      wd(i+1, j, k, itransition2) = wd(i+1, j, k, itransition2) + c2p*&
&       scratchd(i, j, k, istransition2)
      wd(i, j, k, itransition2) = wd(i, j, k, itransition2) - c20*&
&       scratchd(i, j, k, istransition2)
      c1md = w(i-1, j, k, itransition1)*scratchd(i, j, k, istransition1)&
&       + c10d
      wd(i-1, j, k, itransition1) = wd(i-1, j, k, itransition1) + c1m*&
&       scratchd(i, j, k, istransition1)
      c1pd = w(i+1, j, k, itransition1)*scratchd(i, j, k, istransition1)&
&       + c10d
      wd(i+1, j, k, itransition1) = wd(i+1, j, k, itransition1) + c1p*&
&       scratchd(i, j, k, istransition1)
      wd(i, j, k, itransition1) = wd(i, j, k, itransition1) - c10*&
&       scratchd(i, j, k, istransition1)
      tempd0 = rlmsigmathetat*c2pd
      tempd = ttp*rhoi*tempd0
      ttpd = rhoi*(mulp+muep)*tempd0
      rhoid = ttp*(mulp+muep)*tempd0
      mulpd = tempd
      muepd = tempd
      tempd0 = rlmsigmathetat*c2md
      tempd = ttm*rhoi*tempd0
      ttmd = rhoi*(mulm+muem)*tempd0
      rhoid = rhoid + ttm*(mulm+muem)*tempd0
      muemd = tempd
      revd(i+1, j, k) = revd(i+1, j, k) + half*muepd
      revd(i, j, k) = revd(i, j, k) + half*muepd + half*muemd
      muep = half*(rev(i+1, j, k)+rev(i, j, k))
      revd(i-1, j, k) = revd(i-1, j, k) + half*muemd
      muem = half*(rev(i-1, j, k)+rev(i, j, k))
      tempd0 = ttp*rhoi*c1pd
      mulpd = mulpd + tempd0
      muepd = tempd0/rlmsigmaf
      tempd0 = ttm*rhoi*c1md
      mulmd = tempd + tempd0
      tempd = (mulp+muep/rlmsigmaf)*c1pd
      ttpd = ttpd + rhoi*tempd
      rhoid = rhoid + ttp*tempd
      tempd = (mulm+muem/rlmsigmaf)*c1md
      ttmd = ttmd + rhoi*tempd
      rhoid = rhoid + ttm*tempd
      muemd = tempd0/rlmsigmaf
      revd(i+1, j, k) = revd(i+1, j, k) + half*muepd
      revd(i, j, k) = revd(i, j, k) + half*muepd + half*muemd
      revd(i-1, j, k) = revd(i-1, j, k) + half*muemd
      rlvd(i+1, j, k) = rlvd(i+1, j, k) + half*mulpd
      rlvd(i, j, k) = rlvd(i, j, k) + half*mulpd + half*mulmd
      rlvd(i-1, j, k) = rlvd(i-1, j, k) + half*mulmd
      temp0 = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp0**2
      xpd = xa*ttpd
      xad = xp*ttpd + xm*ttmd
      ypd = ya*ttpd
      yad = yp*ttpd + ym*ttmd
      zpd = za*ttpd
      zad = zp*ttpd + zm*ttmd
      xmd = xa*ttmd
      ymd = ya*ttmd
      zmd = za*ttmd
      tempd0 = half*zad
      sid(i, j, k, 3) = sid(i, j, k, 3) + voli*tempd0
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) + voli*tempd0
      volid = (si(i, j, k, 3)+si(i-1, j, k, 3))*tempd0
      tempd0 = half*yad
      sid(i, j, k, 2) = sid(i, j, k, 2) + voli*tempd0
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) + voli*tempd0
      volid = volid + (si(i, j, k, 2)+si(i-1, j, k, 2))*tempd0
      tempd0 = half*xad
      sid(i, j, k, 1) = sid(i, j, k, 1) + voli*tempd0
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) + voli*tempd0
      volid = volid + (si(i, j, k, 1)+si(i-1, j, k, 1))*tempd0
      sid(i, j, k, 3) = sid(i, j, k, 3) + volpi*zpd
      volpid = si(i, j, k, 3)*zpd + si(i, j, k, 2)*ypd + si(i, j, k, 1)*&
&       xpd
      sid(i, j, k, 2) = sid(i, j, k, 2) + volpi*ypd
      sid(i, j, k, 1) = sid(i, j, k, 1) + volpi*xpd
      sid(i-1, j, k, 3) = sid(i-1, j, k, 3) + volmi*zmd
      volmid = si(i-1, j, k, 3)*zmd + si(i-1, j, k, 2)*ymd + si(i-1, j, &
&       k, 1)*xmd
      sid(i-1, j, k, 2) = sid(i-1, j, k, 2) + volmi*ymd
      sid(i-1, j, k, 1) = sid(i-1, j, k, 1) + volmi*xmd
      temp0 = vol(i, j, k) + vol(i+1, j, k)
      tempd0 = -(two*volpid/temp0**2)
      vold(i, j, k) = vold(i, j, k) + tempd0
      vold(i+1, j, k) = vold(i+1, j, k) + tempd0
      temp0 = vol(i, j, k) + vol(i-1, j, k)
      tempd0 = -(two*volmid/temp0**2)
      vold(i-1, j, k) = vold(i-1, j, k) + tempd0
      vold(i, j, k) = vold(i, j, k) + tempd0 - one*volid/vol(i, j, k)**2
    end do
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/deta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the gamma-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j-1, k)+rlv(i, j, k))
      mulp = half*(rlv(i, j+1, k)+rlv(i, j, k))
      muem = half*(rev(i, j-1, k)+rev(i, j, k))
      muep = half*(rev(i, j+1, k)+rev(i, j, k))
      c1m = ttm*(mulm+muem/rlmsigmaf)*rhoi
      c1p = ttp*(mulp+muep/rlmsigmaf)*rhoi
      c10 = c1m + c1p
! and the re_theta_t term.
      muem = half*(rev(i, j-1, k)+rev(i, j, k))
      muep = half*(rev(i, j+1, k)+rev(i, j, k))
      c2m = ttm*rlmsigmathetat*(mulm+muem)*rhoi
      c2p = ttp*rlmsigmathetat*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
! #ifndef 1
!                         b1 = -c1m
!                         c1 = c10
!                         d1 = -c1p
!                         b2 = -c2m
!                         c2 = c20
!                         d2 = -c2p
!                         ! update the central jacobian. for nonboundary cells this
!                         ! is simply c1 and c2. for boundary cells this is slightly
!                         ! more complicated, because the boundary conditions are
!                         ! treated implicitly and the off-diagonal terms b1, b2 and
!                         ! d1, d2 must be taken into account.
!                         ! the boundary conditions are only treated implicitly if
!                         ! the diagonal dominance of the matrix is increased.
!                         if (j == 2) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - b1 * max(bmtj1(i, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - b1 * bmtj1(i, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - b2 * bmtj1(i, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - b2 * max(bmtj1(i, k, itu2, itu2), zero)
!                         else if (j == jl) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - d1 * max(bmtj2(i, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - d1 * bmtj2(i, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - d2 * bmtj2(i, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - d2 * max(bmtj2(i, k, itu2, itu2), zero)
!                         else
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
!                         end if
! #endif
      c10d = -(w(i, j, k, itransition1)*scratchd(i, j, k, istransition1)&
&       )
      c20d = -(w(i, j, k, itransition2)*scratchd(i, j, k, istransition2)&
&       )
      c2md = w(i, j-1, k, itransition2)*scratchd(i, j, k, istransition2)&
&       + c20d
      wd(i, j-1, k, itransition2) = wd(i, j-1, k, itransition2) + c2m*&
&       scratchd(i, j, k, istransition2)
      c2pd = w(i, j+1, k, itransition2)*scratchd(i, j, k, istransition2)&
&       + c20d
      wd(i, j+1, k, itransition2) = wd(i, j+1, k, itransition2) + c2p*&
&       scratchd(i, j, k, istransition2)
      wd(i, j, k, itransition2) = wd(i, j, k, itransition2) - c20*&
&       scratchd(i, j, k, istransition2)
      c1md = w(i, j-1, k, itransition1)*scratchd(i, j, k, istransition1)&
&       + c10d
      wd(i, j-1, k, itransition1) = wd(i, j-1, k, itransition1) + c1m*&
&       scratchd(i, j, k, istransition1)
      c1pd = w(i, j+1, k, itransition1)*scratchd(i, j, k, istransition1)&
&       + c10d
      wd(i, j+1, k, itransition1) = wd(i, j+1, k, itransition1) + c1p*&
&       scratchd(i, j, k, istransition1)
      wd(i, j, k, itransition1) = wd(i, j, k, itransition1) - c10*&
&       scratchd(i, j, k, istransition1)
      tempd0 = rlmsigmathetat*c2pd
      tempd = ttp*rhoi*tempd0
      ttpd = rhoi*(mulp+muep)*tempd0
      rhoid = ttp*(mulp+muep)*tempd0
      mulpd = tempd
      muepd = tempd
      tempd0 = rlmsigmathetat*c2md
      tempd = ttm*rhoi*tempd0
      ttmd = rhoi*(mulm+muem)*tempd0
      rhoid = rhoid + ttm*(mulm+muem)*tempd0
      muemd = tempd
      revd(i, j+1, k) = revd(i, j+1, k) + half*muepd
      revd(i, j, k) = revd(i, j, k) + half*muepd + half*muemd
      muep = half*(rev(i, j+1, k)+rev(i, j, k))
      revd(i, j-1, k) = revd(i, j-1, k) + half*muemd
      muem = half*(rev(i, j-1, k)+rev(i, j, k))
      tempd0 = ttp*rhoi*c1pd
      mulpd = mulpd + tempd0
      muepd = tempd0/rlmsigmaf
      tempd0 = ttm*rhoi*c1md
      mulmd = tempd + tempd0
      tempd = (mulp+muep/rlmsigmaf)*c1pd
      ttpd = ttpd + rhoi*tempd
      rhoid = rhoid + ttp*tempd
      tempd = (mulm+muem/rlmsigmaf)*c1md
      ttmd = ttmd + rhoi*tempd
      rhoid = rhoid + ttm*tempd
      muemd = tempd0/rlmsigmaf
      revd(i, j+1, k) = revd(i, j+1, k) + half*muepd
      revd(i, j, k) = revd(i, j, k) + half*muepd + half*muemd
      revd(i, j-1, k) = revd(i, j-1, k) + half*muemd
      rlvd(i, j+1, k) = rlvd(i, j+1, k) + half*mulpd
      rlvd(i, j, k) = rlvd(i, j, k) + half*mulpd + half*mulmd
      rlvd(i, j-1, k) = rlvd(i, j-1, k) + half*mulmd
      temp0 = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp0**2
      xpd = xa*ttpd
      xad = xp*ttpd + xm*ttmd
      ypd = ya*ttpd
      yad = yp*ttpd + ym*ttmd
      zpd = za*ttpd
      zad = zp*ttpd + zm*ttmd
      xmd = xa*ttmd
      ymd = ya*ttmd
      zmd = za*ttmd
      tempd0 = half*zad
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + voli*tempd0
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) + voli*tempd0
      volid = (sj(i, j, k, 3)+sj(i, j-1, k, 3))*tempd0
      tempd0 = half*yad
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + voli*tempd0
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) + voli*tempd0
      volid = volid + (sj(i, j, k, 2)+sj(i, j-1, k, 2))*tempd0
      tempd0 = half*xad
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + voli*tempd0
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) + voli*tempd0
      volid = volid + (sj(i, j, k, 1)+sj(i, j-1, k, 1))*tempd0
      sjd(i, j, k, 3) = sjd(i, j, k, 3) + volpi*zpd
      volpid = sj(i, j, k, 3)*zpd + sj(i, j, k, 2)*ypd + sj(i, j, k, 1)*&
&       xpd
      sjd(i, j, k, 2) = sjd(i, j, k, 2) + volpi*ypd
      sjd(i, j, k, 1) = sjd(i, j, k, 1) + volpi*xpd
      sjd(i, j-1, k, 3) = sjd(i, j-1, k, 3) + volmi*zmd
      volmid = sj(i, j-1, k, 3)*zmd + sj(i, j-1, k, 2)*ymd + sj(i, j-1, &
&       k, 1)*xmd
      sjd(i, j-1, k, 2) = sjd(i, j-1, k, 2) + volmi*ymd
      sjd(i, j-1, k, 1) = sjd(i, j-1, k, 1) + volmi*xmd
      temp0 = vol(i, j, k) + vol(i, j+1, k)
      tempd0 = -(two*volpid/temp0**2)
      vold(i, j, k) = vold(i, j, k) + tempd0
      vold(i, j+1, k) = vold(i, j+1, k) + tempd0
      temp0 = vol(i, j, k) + vol(i, j-1, k)
      tempd0 = -(two*volmid/temp0**2)
      vold(i, j-1, k) = vold(i, j-1, k) + tempd0
      vold(i, j, k) = vold(i, j, k) + tempd0 - one*volid/vol(i, j, k)**2
    end do
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dzeta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the gamma-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j, k-1)+rlv(i, j, k))
      mulp = half*(rlv(i, j, k+1)+rlv(i, j, k))
      muem = half*(rev(i, j, k-1)+rev(i, j, k))
      muep = half*(rev(i, j, k+1)+rev(i, j, k))
      c1m = ttm*(mulm+muem/rlmsigmaf)*rhoi
      c1p = ttp*(mulp+muep/rlmsigmaf)*rhoi
      c10 = c1m + c1p
! and the re_theta_t term.
      muem = half*(rev(i, j, k-1)+rev(i, j, k))
      muep = half*(rev(i, j, k+1)+rev(i, j, k))
      c2m = ttm*rlmsigmathetat*(mulm+muem)*rhoi
      c2p = ttp*rlmsigmathetat*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
! #ifndef 1
!                         b1 = -c1m
!                         c1 = c10
!                         d1 = -c1p
!                         b2 = -c2m
!                         c2 = c20
!                         d2 = -c2p
!                         ! update the central jacobian. for nonboundary cells this
!                         ! is simply c1 and c2. for boundary cells this is slightly
!                         ! more complicated, because the boundary conditions are
!                         ! treated implicitly and the off-diagonal terms b1, b2 and
!                         ! d1, d2 must be taken into account.
!                         ! the boundary conditions are only treated implicitly if
!                         ! the diagonal dominance of the matrix is increased.
!                         if (k == 2) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - b1 * max(bmtk1(i, j, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - b1 * bmtk1(i, j, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - b2 * bmtk1(i, j, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - b2 * max(bmtk1(i, j, itu2, itu2), zero)
!                         else if (k == kl) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - d1 * max(bmtk2(i, j, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - d1 * bmtk2(i, j, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - d2 * bmtk2(i, j, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - d2 * max(bmtk2(i, j, itu2, itu2), zero)
!                         else
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
!                         end if
! #endif
      c10d = -(w(i, j, k, itransition1)*scratchd(i, j, k, istransition1)&
&       )
      c20d = -(w(i, j, k, itransition2)*scratchd(i, j, k, istransition2)&
&       )
      c2md = w(i, j, k-1, itransition2)*scratchd(i, j, k, istransition2)&
&       + c20d
      wd(i, j, k-1, itransition2) = wd(i, j, k-1, itransition2) + c2m*&
&       scratchd(i, j, k, istransition2)
      c2pd = w(i, j, k+1, itransition2)*scratchd(i, j, k, istransition2)&
&       + c20d
      wd(i, j, k+1, itransition2) = wd(i, j, k+1, itransition2) + c2p*&
&       scratchd(i, j, k, istransition2)
      wd(i, j, k, itransition2) = wd(i, j, k, itransition2) - c20*&
&       scratchd(i, j, k, istransition2)
      c1md = w(i, j, k-1, itransition1)*scratchd(i, j, k, istransition1)&
&       + c10d
      wd(i, j, k-1, itransition1) = wd(i, j, k-1, itransition1) + c1m*&
&       scratchd(i, j, k, istransition1)
      c1pd = w(i, j, k+1, itransition1)*scratchd(i, j, k, istransition1)&
&       + c10d
      wd(i, j, k+1, itransition1) = wd(i, j, k+1, itransition1) + c1p*&
&       scratchd(i, j, k, istransition1)
      wd(i, j, k, itransition1) = wd(i, j, k, itransition1) - c10*&
&       scratchd(i, j, k, istransition1)
      tempd0 = rlmsigmathetat*c2pd
      tempd = ttp*rhoi*tempd0
      ttpd = rhoi*(mulp+muep)*tempd0
      rhoid = ttp*(mulp+muep)*tempd0
      mulpd = tempd
      muepd = tempd
      tempd0 = rlmsigmathetat*c2md
      tempd = ttm*rhoi*tempd0
      ttmd = rhoi*(mulm+muem)*tempd0
      rhoid = rhoid + ttm*(mulm+muem)*tempd0
      mulmd = tempd
      muemd = tempd
      revd(i, j, k+1) = revd(i, j, k+1) + half*muepd
      revd(i, j, k) = revd(i, j, k) + half*muepd + half*muemd
      muep = half*(rev(i, j, k+1)+rev(i, j, k))
      revd(i, j, k-1) = revd(i, j, k-1) + half*muemd
      muem = half*(rev(i, j, k-1)+rev(i, j, k))
      tempd0 = ttp*rhoi*c1pd
      tempd = (mulp+muep/rlmsigmaf)*c1pd
      ttpd = ttpd + rhoi*tempd
      mulpd = mulpd + tempd0
      muepd = tempd0/rlmsigmaf
      tempd0 = (mulm+muem/rlmsigmaf)*c1md
      rhoid = rhoid + ttp*tempd + ttm*tempd0
      tempd = ttm*rhoi*c1md
      ttmd = ttmd + rhoi*tempd0
      mulmd = mulmd + tempd
      muemd = tempd/rlmsigmaf
      revd(i, j, k+1) = revd(i, j, k+1) + half*muepd
      revd(i, j, k) = revd(i, j, k) + half*muepd + half*muemd
      revd(i, j, k-1) = revd(i, j, k-1) + half*muemd
      rlvd(i, j, k+1) = rlvd(i, j, k+1) + half*mulpd
      rlvd(i, j, k) = rlvd(i, j, k) + half*mulpd + half*mulmd
      rlvd(i, j, k-1) = rlvd(i, j, k-1) + half*mulmd
      temp = w(i, j, k, irho)
      wd(i, j, k, irho) = wd(i, j, k, irho) - one*rhoid/temp**2
      xpd = xa*ttpd
      xad = xp*ttpd + xm*ttmd
      ypd = ya*ttpd
      yad = yp*ttpd + ym*ttmd
      zpd = za*ttpd
      zad = zp*ttpd + zm*ttmd
      xmd = xa*ttmd
      ymd = ya*ttmd
      zmd = za*ttmd
      tempd = half*zad
      skd(i, j, k, 3) = skd(i, j, k, 3) + voli*tempd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) + voli*tempd
      volid = (sk(i, j, k, 3)+sk(i, j, k-1, 3))*tempd
      tempd = half*yad
      skd(i, j, k, 2) = skd(i, j, k, 2) + voli*tempd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) + voli*tempd
      volid = volid + (sk(i, j, k, 2)+sk(i, j, k-1, 2))*tempd
      tempd = half*xad
      skd(i, j, k, 1) = skd(i, j, k, 1) + voli*tempd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) + voli*tempd
      volid = volid + (sk(i, j, k, 1)+sk(i, j, k-1, 1))*tempd
      skd(i, j, k, 3) = skd(i, j, k, 3) + volpi*zpd
      volpid = sk(i, j, k, 3)*zpd + sk(i, j, k, 2)*ypd + sk(i, j, k, 1)*&
&       xpd
      skd(i, j, k, 2) = skd(i, j, k, 2) + volpi*ypd
      skd(i, j, k, 1) = skd(i, j, k, 1) + volpi*xpd
      skd(i, j, k-1, 3) = skd(i, j, k-1, 3) + volmi*zmd
      volmid = sk(i, j, k-1, 3)*zmd + sk(i, j, k-1, 2)*ymd + sk(i, j, k-&
&       1, 1)*xmd
      skd(i, j, k-1, 2) = skd(i, j, k-1, 2) + volmi*ymd
      skd(i, j, k-1, 1) = skd(i, j, k-1, 1) + volmi*xmd
      temp = vol(i, j, k) + vol(i, j, k+1)
      tempd = -(two*volpid/temp**2)
      vold(i, j, k) = vold(i, j, k) + tempd
      vold(i, j, k+1) = vold(i, j, k+1) + tempd
      temp = vol(i, j, k) + vol(i, j, k-1)
      tempd = -(two*volmid/temp**2)
      vold(i, j, k-1) = vold(i, j, k-1) + tempd
      vold(i, j, k) = vold(i, j, k) + tempd - one*volid/vol(i, j, k)**2
    end do
  end subroutine gammarethetaviscous_b

  subroutine gammarethetaviscous()
    use blockpointers
    use constants
    use variableconstants
    use paramturb
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rhoi
    real(kind=realtype) :: voli, volmi, volpi
    real(kind=realtype) :: xm, ym, zm, xp, yp, zp, xa, ya, za
    real(kind=realtype) :: mulm, mulp, muem, muep
    real(kind=realtype) :: ttm, ttp
    real(kind=realtype) :: c1m, c1p, c10, c2m, c2p, c20
    real(kind=realtype) :: rblank
    intrinsic mod
!$ad ii-loop
!       advection and unsteady terms.
!
!
!       viscous terms in k-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in zeta-direction, i.e. along the
! line k = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j, k-1))
      volpi = two/(vol(i, j, k)+vol(i, j, k+1))
      xm = sk(i, j, k-1, 1)*volmi
      ym = sk(i, j, k-1, 2)*volmi
      zm = sk(i, j, k-1, 3)*volmi
      xp = sk(i, j, k, 1)*volpi
      yp = sk(i, j, k, 2)*volpi
      zp = sk(i, j, k, 3)*volpi
      xa = half*(sk(i, j, k, 1)+sk(i, j, k-1, 1))*voli
      ya = half*(sk(i, j, k, 2)+sk(i, j, k-1, 2))*voli
      za = half*(sk(i, j, k, 3)+sk(i, j, k-1, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in zeta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in zeta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dzeta^2 = d/dzeta (d/dzeta k+1/2 - d/dzeta k-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dzeta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the gamma-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j, k-1)+rlv(i, j, k))
      mulp = half*(rlv(i, j, k+1)+rlv(i, j, k))
      muem = half*(rev(i, j, k-1)+rev(i, j, k))
      muep = half*(rev(i, j, k+1)+rev(i, j, k))
      c1m = ttm*(mulm+muem/rlmsigmaf)*rhoi
      c1p = ttp*(mulp+muep/rlmsigmaf)*rhoi
      c10 = c1m + c1p
! and the re_theta_t term.
      muem = half*(rev(i, j, k-1)+rev(i, j, k))
      muep = half*(rev(i, j, k+1)+rev(i, j, k))
      c2m = ttm*rlmsigmathetat*(mulm+muem)*rhoi
      c2p = ttp*rlmsigmathetat*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, istransition1) = scratch(i, j, k, istransition1) &
&       + c1m*w(i, j, k-1, itransition1) - c10*w(i, j, k, itransition1) &
&       + c1p*w(i, j, k+1, itransition1)
      scratch(i, j, k, istransition2) = scratch(i, j, k, istransition2) &
&       + c2m*w(i, j, k-1, itransition2) - c20*w(i, j, k, itransition2) &
&       + c2p*w(i, j, k+1, itransition2)
! #ifndef 1
!                         b1 = -c1m
!                         c1 = c10
!                         d1 = -c1p
!                         b2 = -c2m
!                         c2 = c20
!                         d2 = -c2p
!                         ! update the central jacobian. for nonboundary cells this
!                         ! is simply c1 and c2. for boundary cells this is slightly
!                         ! more complicated, because the boundary conditions are
!                         ! treated implicitly and the off-diagonal terms b1, b2 and
!                         ! d1, d2 must be taken into account.
!                         ! the boundary conditions are only treated implicitly if
!                         ! the diagonal dominance of the matrix is increased.
!                         if (k == 2) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - b1 * max(bmtk1(i, j, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - b1 * bmtk1(i, j, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - b2 * bmtk1(i, j, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - b2 * max(bmtk1(i, j, itu2, itu2), zero)
!                         else if (k == kl) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - d1 * max(bmtk2(i, j, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - d1 * bmtk2(i, j, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - d2 * bmtk2(i, j, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - d2 * max(bmtk2(i, j, itu2, itu2), zero)
!                         else
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
!                         end if
! #endif
    end do
!$ad ii-loop
!
!       viscous terms in j-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in eta-direction, i.e. along the
! line j = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i, j-1, k))
      volpi = two/(vol(i, j, k)+vol(i, j+1, k))
      xm = sj(i, j-1, k, 1)*volmi
      ym = sj(i, j-1, k, 2)*volmi
      zm = sj(i, j-1, k, 3)*volmi
      xp = sj(i, j, k, 1)*volpi
      yp = sj(i, j, k, 2)*volpi
      zp = sj(i, j, k, 3)*volpi
      xa = half*(sj(i, j, k, 1)+sj(i, j-1, k, 1))*voli
      ya = half*(sj(i, j, k, 2)+sj(i, j-1, k, 2))*voli
      za = half*(sj(i, j, k, 3)+sj(i, j-1, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in eta-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in eta-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/deta^2 = d/deta (d/deta j+1/2 - d/deta j-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/deta derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the gamma-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i, j-1, k)+rlv(i, j, k))
      mulp = half*(rlv(i, j+1, k)+rlv(i, j, k))
      muem = half*(rev(i, j-1, k)+rev(i, j, k))
      muep = half*(rev(i, j+1, k)+rev(i, j, k))
      c1m = ttm*(mulm+muem/rlmsigmaf)*rhoi
      c1p = ttp*(mulp+muep/rlmsigmaf)*rhoi
      c10 = c1m + c1p
! and the re_theta_t term.
      muem = half*(rev(i, j-1, k)+rev(i, j, k))
      muep = half*(rev(i, j+1, k)+rev(i, j, k))
      c2m = ttm*rlmsigmathetat*(mulm+muem)*rhoi
      c2p = ttp*rlmsigmathetat*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, istransition1) = scratch(i, j, k, istransition1) &
&       + c1m*w(i, j-1, k, itransition1) - c10*w(i, j, k, itransition1) &
&       + c1p*w(i, j+1, k, itransition1)
      scratch(i, j, k, istransition2) = scratch(i, j, k, istransition2) &
&       + c2m*w(i, j-1, k, itransition2) - c20*w(i, j, k, itransition2) &
&       + c2p*w(i, j+1, k, itransition2)
! #ifndef 1
!                         b1 = -c1m
!                         c1 = c10
!                         d1 = -c1p
!                         b2 = -c2m
!                         c2 = c20
!                         d2 = -c2p
!                         ! update the central jacobian. for nonboundary cells this
!                         ! is simply c1 and c2. for boundary cells this is slightly
!                         ! more complicated, because the boundary conditions are
!                         ! treated implicitly and the off-diagonal terms b1, b2 and
!                         ! d1, d2 must be taken into account.
!                         ! the boundary conditions are only treated implicitly if
!                         ! the diagonal dominance of the matrix is increased.
!                         if (j == 2) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - b1 * max(bmtj1(i, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - b1 * bmtj1(i, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - b2 * bmtj1(i, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - b2 * max(bmtj1(i, k, itu2, itu2), zero)
!                         else if (j == jl) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - d1 * max(bmtj2(i, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - d1 * bmtj2(i, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - d2 * bmtj2(i, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - d2 * max(bmtj2(i, k, itu2, itu2), zero)
!                         else
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
!                         end if
! #endif
    end do
!$ad ii-loop
!
!       viscous terms in i-direction.
!
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
! compute the metrics in xi-direction, i.e. along the
! line i = constant.
      voli = one/vol(i, j, k)
      volmi = two/(vol(i, j, k)+vol(i-1, j, k))
      volpi = two/(vol(i, j, k)+vol(i+1, j, k))
      xm = si(i-1, j, k, 1)*volmi
      ym = si(i-1, j, k, 2)*volmi
      zm = si(i-1, j, k, 3)*volmi
      xp = si(i, j, k, 1)*volpi
      yp = si(i, j, k, 2)*volpi
      zp = si(i, j, k, 3)*volpi
      xa = half*(si(i, j, k, 1)+si(i-1, j, k, 1))*voli
      ya = half*(si(i, j, k, 2)+si(i-1, j, k, 2))*voli
      za = half*(si(i, j, k, 3)+si(i-1, j, k, 3))*voli
      ttm = xm*xa + ym*ya + zm*za
      ttp = xp*xa + yp*ya + zp*za
! computation of the viscous terms in xi-direction; note
! that cross-derivatives are neglected, i.e. the mesh is
! assumed to be orthogonal.
! the second derivative in xi-direction is constructed as
! the central difference of the first order derivatives, i.e.
! d^2/dxi^2 = d/dxi (d/dxi i+1/2 - d/dxi i-1/2).
! in this way the metric as well as the varying viscosity
! can be taken into account; the latter appears inside the
! d/dxi derivative. the whole term is divided by rho to
! obtain the diffusion term for k and omega.
! first the gamma-term.
      rhoi = one/w(i, j, k, irho)
      mulm = half*(rlv(i-1, j, k)+rlv(i, j, k))
      mulp = half*(rlv(i+1, j, k)+rlv(i, j, k))
      muem = half*(rev(i-1, j, k)+rev(i, j, k))
      muep = half*(rev(i+1, j, k)+rev(i, j, k))
      c1m = ttm*(mulm+muem/rlmsigmaf)*rhoi
      c1p = ttp*(mulp+muep/rlmsigmaf)*rhoi
      c10 = c1m + c1p
! and the re_theta_t term.
      muem = half*(rev(i-1, j, k)+rev(i, j, k))
      muep = half*(rev(i+1, j, k)+rev(i, j, k))
      c2m = ttm*rlmsigmathetat*(mulm+muem)*rhoi
      c2p = ttp*rlmsigmathetat*(mulp+muep)*rhoi
      c20 = c2m + c2p
! update the residual for this cell and store the possible
! coefficients for the matrix in b1, b2, c1, c2, d1 and d2.
      scratch(i, j, k, istransition1) = scratch(i, j, k, istransition1) &
&       + c1m*w(i-1, j, k, itransition1) - c10*w(i, j, k, itransition1) &
&       + c1p*w(i+1, j, k, itransition1)
      scratch(i, j, k, istransition2) = scratch(i, j, k, istransition2) &
&       + c2m*w(i-1, j, k, itransition2) - c20*w(i, j, k, itransition2) &
&       + c2p*w(i+1, j, k, itransition2)
! #ifndef 1
!                         b1 = -c1m
!                         c1 = c10
!                         d1 = -c1p
!                         b2 = -c2m
!                         c2 = c20
!                         d2 = -c2p
!                         ! update the central jacobian. for nonboundary cells this
!                         ! is simply c1 and c2. for boundary cells this is slightly
!                         ! more complicated, because the boundary conditions are
!                         ! treated implicitly and the off-diagonal terms b1, b2 and
!                         ! d1, d2 must be taken into account.
!                         ! the boundary conditions are only treated implicitly if
!                         ! the diagonal dominance of the matrix is increased.
!                         if (i == 2) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - b1 * max(bmti1(j, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - b1 * bmti1(j, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - b2 * bmti1(j, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - b2 * max(bmti1(j, k, itu2, itu2), zero)
!                         else if (i == il) then
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1 &
!                                                 - d1 * max(bmti2(j, k, itu1, itu1), zero)
!                             qq(i, j, k, 1, 2) = qq(i, j, k, 1, 2) - d1 * bmti2(j, k, itu1, itu2)
!                             qq(i, j, k, 2, 1) = qq(i, j, k, 2, 1) - d2 * bmti2(j, k, itu2, itu1)
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2 &
!                                                 - d2 * max(bmti2(j, k, itu2, itu2), zero)
!                         else
!                             qq(i, j, k, 1, 1) = qq(i, j, k, 1, 1) + c1
!                             qq(i, j, k, 2, 2) = qq(i, j, k, 2, 2) + c2
!                         end if
! #endif
    end do
  end subroutine gammarethetaviscous

!  differentiation of gammarethetaresscale in reverse (adjoint) mode (with options noisize i4 dr8 r8):
!   gradient     of useful results: *dw *scratch
!   with respect to varying inputs: *dw *scratch
!   rw status of diff variables: *dw:in-out *scratch:incr
!   plus diff mem management of: dw:in scratch:in
  subroutine gammarethetaresscale_b()
    use blockpointers
    use constants
    use variableconstants
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
!$bwd-of ii-loop 
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      rblank = real(iblank(i, j, k), realtype)
! print *, 'dw transition 1 & 2', dw(i, j, k, itransition1), dw(i, j, k, itransition2)
      scratchd(i, j, k, istransition2) = scratchd(i, j, k, istransition2&
&       ) - volref(i, j, k)*rblank*dwd(i, j, k, itransition2)
      dwd(i, j, k, itransition2) = 0.0_8
      scratchd(i, j, k, istransition1) = scratchd(i, j, k, istransition1&
&       ) - volref(i, j, k)*rblank*dwd(i, j, k, itransition1)
      dwd(i, j, k, itransition1) = 0.0_8
    end do
  end subroutine gammarethetaresscale_b

  subroutine gammarethetaresscale()
    use blockpointers
    use constants
    use variableconstants
    implicit none
!
!      local variables.
!
    integer(kind=inttype) :: i, j, k, ii
    real(kind=realtype) :: rblank
    intrinsic mod
    intrinsic real
!$ad ii-loop
! multiply the residual by the volume and store this in dw; this
! is done for monitoring reasons only. the multiplication with the
! volume is present to be consistent with the flow residuals; also
! the negative value is taken, again to be consistent with the
! flow equations. also multiply by iblank so that no updates occur
! in holes or the overset boundary.
    do ii=0,nx*ny*nz-1
      i = mod(ii, nx) + 2
      j = mod(ii/nx, ny) + 2
      k = ii/(nx*ny) + 2
      rblank = real(iblank(i, j, k), realtype)
      dw(i, j, k, itransition1) = -(volref(i, j, k)*scratch(i, j, k, &
&       istransition1)*rblank)
      dw(i, j, k, itransition2) = -(volref(i, j, k)*scratch(i, j, k, &
&       istransition2)*rblank)
! print *, 'dw transition 1 & 2', dw(i, j, k, itransition1), dw(i, j, k, itransition2)
    end do
  end subroutine gammarethetaresscale

end module gammarethetamodel_b

